const SRC = 'A curated, high-yield selection covering the standard prelims-level static GK syllabus for Indian history and culture, compiled from NCERT-level references and standard competitive-exam material. Indian history is vast — this file deliberately prioritises the facts, figures and associations most consistently tested across state PSC prelims rather than attempting textbook-level exhaustiveness. Uttarakhand-specific history is covered separately and in far greater depth under the Uttarakhand section.';

const p = (heading, type, ...paragraphs) => ({ heading, type, paragraphs });
const s = (heading, type, ...bullets) => ({ heading, type, bullets });

export const historyTopics = {
  'Ancient India': {
    priority: 'MUST KNOW', title: 'Ancient India',
    summary: 'From the urban Indus Valley Civilization through the Vedic Age, the rise of Buddhism and Jainism, the Mauryan and Gupta empires, ancient Indian history is tested heavily on site names, ruler-achievement associations, and religious/scientific milestones.',
    sections: [
      p('1. The Indus Valley Civilization', 'must',
        'The Indus Valley (Harappan) Civilization, one of the world\'s earliest urban civilizations (roughly 2500-1750 BCE at its mature phase), is known for remarkably planned cities with grid-pattern streets, covered drainage systems and standardised burnt-brick construction — a striking contrast to the more loosely organised settlements of contemporary civilizations. Key sites each carry a distinguishing feature worth memorising individually: Mohenjo-daro (Sindh, on the Indus) is famous for the Great Bath, a large public water tank; Harappa (Punjab, on the Ravi) gave the civilization its name; Dholavira (Gujarat) is notable for its sophisticated water conservation/reservoir system and a unique signboard inscription; Lothal (Gujarat) had a dockyard, pointing to maritime trade; and Kalibangan (Rajasthan) has evidence of ploughed fields. The script remains undeciphered, the civilization\'s decline is debated (climate change and river shifts are leading theories), and its economy relied heavily on trade, including with Mesopotamia.'),
      p('2. The Vedic Age', 'must',
        'The Vedic Age (roughly 1500-600 BCE) is divided into the Early (Rig) Vedic period, centred on pastoral, tribal society along the Indus-Saraswati belt with the Rigveda as its primary text, and the Later Vedic period, marked by eastward expansion into the Gangetic plains, the rise of settled agriculture, iron tools, the emergence of the four varnas as a more rigid social structure, and the composition of the later three Vedas (Sama, Yajur, Atharva) plus the Brahmanas, Aranyakas and Upanishads. This period also saw the earliest ideas later systematised into classical Hindu philosophy and ritual.'),
      p('3. Rise of Buddhism and Jainism', 'must',
        'Both religions emerged around the 6th century BCE, in the context of the sixteen Mahajanapadas (major territorial states, of which Magadha ultimately rose to dominance) and a reaction against Vedic ritualism and the rigidity of the varna system. Gautama Buddha (born Siddhartha, at Lumbini, attained enlightenment at Bodh Gaya, gave his first sermon at Sarnath, died/attained Mahaparinirvana at Kushinagar — the "four holy sites" worth memorising as a set) taught the Four Noble Truths and the Eightfold Path, rejecting the authority of the Vedas and caste distinctions in principle. Mahavira (the 24th Tirthankara of Jainism, a contemporary of the Buddha) taught the doctrine of Ahimsa (non-violence) as central, along with the Three Jewels (Right Faith, Right Knowledge, Right Conduct). Both religions were patronised by Magadhan rulers and spread significantly under later imperial support, most famously Ashoka\'s for Buddhism.'),
      p('4. The Mauryan Empire', 'must',
        'Chandragupta Maurya founded the Mauryan Empire (c. 321 BCE) with the guidance of his mentor Chanakya (Kautilya), author of the Arthashastra, a treatise on statecraft and economics. Ashoka, Chandragupta\'s grandson, is the dynasty\'s most historically significant ruler: after the bloody Kalinga War (c. 261 BCE), he embraced Buddhism and propagated Dhamma (a code of ethical conduct emphasising non-violence, tolerance and welfare) through edicts inscribed on rocks and pillars across the empire — the Ashokan pillar at Sarnath, with its four-lion capital, is now India\'s National Emblem, and his edicts are a key primary-source basis for reconstructing Mauryan history.'),
      p('5. The Gupta Empire: a classical "golden age"', 'must',
        'The Gupta Empire (c. 320-550 CE), founded by Chandragupta I, is conventionally described as a golden age of classical Indian civilization for its achievements in science, mathematics, astronomy, art and literature. Samudragupta, often called the "Napoleon of India" for his extensive military conquests, and Chandragupta II ("Vikramaditya"), under whose reign the Chinese pilgrim Fa-Hien visited India and left an important travel account, are the dynasty\'s two most prominent rulers. The period produced Aryabhata (astronomy, and early use of zero-related concepts), Kalidasa (Sanskrit poet-playwright, author of Abhijnanasakuntalam), and significant advances in metallurgy (the rust-resistant Iron Pillar of Delhi). Harsha, ruling in the 7th century after the Gupta decline, is the last major ancient Indian emperor before the fragmentation into regional kingdoms that defines the transition to the medieval period; the Chinese traveller Hiuen Tsang visited during his reign.'),
      s('6. What to memorize', 'must',
        'Harappan sites: Mohenjo-daro (Great Bath), Harappa (namesake), Dholavira (water reservoirs), Lothal (dockyard), Kalibangan (ploughed field)',
        'Buddha\'s four sites: Lumbini (birth), Bodh Gaya (enlightenment), Sarnath (first sermon), Kushinagar (death)',
        'Mauryas: Chandragupta + Chanakya (Arthashastra); Ashoka — Kalinga War → Dhamma, Sarnath pillar → National Emblem',
        'Guptas: Chandragupta I (founder), Samudragupta ("Napoleon of India"), Chandragupta II (Fa-Hien visited); Aryabhata, Kalidasa'),
      s('7. Exam traps', 'trap',
        'Fa-Hien visited during Chandragupta II\'s reign; Hiuen Tsang visited during Harsha\'s reign — a frequently swapped traveller-ruler pairing.',
        'The Indus script remains undeciphered — do not treat any claimed "reading" of it as established fact.',
        'Mahavira was the 24th Tirthankara, not the founder of Jainism as a wholly new religion — Jain tradition holds the lineage predates him.'),
      s('8. 30-second revision', 'revision',
        'IVC: Mohenjo-daro=Bath, Harappa=name, Dholavira=water, Lothal=dock. Buddha: Lumbini-BodhGaya-Sarnath-Kushinagar. Mauryas: Chandragupta+Chanakya; Ashoka=Kalinga→Dhamma. Guptas: golden age, Samudragupta, Chandragupta II+Fa-Hien, Aryabhata, Kalidasa. Harsha+Hiuen Tsang = transition to medieval.')
    ],
    sourceNote: SRC
  },

  'Medieval India': {
    priority: 'MUST KNOW', title: 'Medieval India',
    summary: 'Medieval India spans the Delhi Sultanate\'s five dynasties, the Vijayanagara-Bahmani rivalry in the south, the Bhakti-Sufi devotional movements, and the Mughal Empire from Babur to Aurangzeb — a period tested heavily on dynasty sequencing and ruler-specific achievements.',
    sections: [
      p('1. The Delhi Sultanate: five dynasties', 'must',
        'The Delhi Sultanate (1206-1526) ran through five successive dynasties, a sequence worth memorising in order: the Mamluk/Slave Dynasty (1206-90, founded by Qutbuddin Aibak, who began the Qutub Minar; Iltutmish consolidated the Sultanate; Razia Sultan, Iltutmish\'s daughter, was the only woman to rule as Sultan of Delhi), the Khilji Dynasty (1290-1320, dominated by Alauddin Khilji, known for market-control reforms and successfully repelling Mongol invasions), the Tughlaq Dynasty (1320-1414, Muhammad bin Tughlaq is infamous for the failed transfer of capital to Daulatabad and token currency experiment), the Sayyid Dynasty (1414-51) and the Lodi Dynasty (1451-1526, the only Afghan/Pashtun dynasty of the Sultanate, ending with Ibrahim Lodi\'s defeat at the First Battle of Panipat, 1526, which brought the Mughals to power).'),
      p('2. Vijayanagara and Bahmani kingdoms', 'must',
        'In the south, the Vijayanagara Empire (founded 1336, capital at Hampi) and the Bahmani Sultanate (founded 1347, in the Deccan) emerged as major, often rival, powers — Vijayanagara reached its peak under Krishnadevaraya (early 16th century), a notable patron of Telugu and Sanskrit literature and temple architecture, before the empire\'s decisive defeat at the Battle of Talikota (1565) by a coalition of Deccan Sultanates (successor states to the fragmented Bahmani kingdom), leading to Hampi\'s destruction and the empire\'s long decline.'),
      p('3. Bhakti and Sufi movements', 'must',
        'The Bhakti movement, a devotional Hindu tradition emphasising personal devotion to a chosen deity over ritual and caste distinctions, produced influential poet-saints across regions and languages: Kabir (syncretic, critical of both Hindu and Muslim orthodoxy), Guru Nanak (founder of Sikhism, drawing on both Bhakti and Sufi ideas), Mirabai (Krishna devotion, Rajasthan), Tulsidas (author of the Ramcharitmanas, an Awadhi retelling of the Ramayana), and Chaitanya Mahaprabhu (Bengal, Krishna devotion). Parallel to this, the Sufi movement, a mystical strand within Islam emphasising personal spiritual experience over legalistic orthodoxy, produced influential orders (silsilas) in India, most notably the Chishti order (Moinuddin Chishti at Ajmer, Nizamuddin Auliya at Delhi) — both movements together fostered considerable syncretic cultural exchange between Hindu and Muslim traditions in medieval India.'),
      p('4. The Mughal Empire: Babur to Aurangzeb', 'must',
        'Babur founded the Mughal Empire after defeating Ibrahim Lodi at Panipat (1526); his son Humayun briefly lost the throne to Sher Shah Suri (an Afghan ruler notable for administrative reforms, including the Grand Trunk Road and a revenue system that influenced later Mughal administration) before regaining it. Akbar, the empire\'s greatest consolidator, is remembered for the Mansabdari system (a ranked administrative-military hierarchy), religious tolerance (abolishing the jizya tax on non-Muslims, and founding Din-i-Ilahi, a syncretic faith), and expanding the empire\'s territorial and administrative reach. Jahangir and Shah Jahan followed; Shah Jahan\'s reign is most associated with Mughal architecture\'s peak, especially the Taj Mahal (built for his wife Mumtaz Mahal). Aurangzeb, the last of the major "Great Mughals," pursued extensive military expansion but reversed several of Akbar\'s tolerant policies (reimposing the jizya), and his long reign is generally seen as the point after which Mughal central authority began a sustained decline, coinciding with the rise of regional powers like the Marathas.'),
      p('5. Rise of the Marathas', 'understand',
        'Shivaji, founder of the Maratha kingdom, is celebrated for his military strategy (guerrilla warfare, hill-fort-based defence) and administrative system (the Ashtapradhan council of eight ministers), formally crowning himself Chhatrapati in 1674 — the Marathas subsequently expanded into a major power challenging Mughal authority across large parts of India through the 18th century, eventually becoming the dominant regional power before British expansion.'),
      s('6. What to memorize', 'must',
        'Delhi Sultanate order: Slave (Aibak, Iltutmish, Razia) → Khilji (Alauddin) → Tughlaq (Muhammad bin) → Sayyid → Lodi (Ibrahim, defeated 1526)',
        'Vijayanagara: Krishnadevaraya (peak) → Battle of Talikota 1565 (defeat by Deccan Sultanates)',
        'Bhakti saints: Kabir, Guru Nanak, Mirabai, Tulsidas (Ramcharitmanas), Chaitanya; Sufi: Chishti order (Ajmer, Delhi)',
        'Mughals: Babur (1526, Panipat I) → Humayun (interrupted by Sher Shah Suri) → Akbar (Mansabdari, Din-i-Ilahi) → Jahangir → Shah Jahan (Taj Mahal) → Aurangzeb (expansion + decline begins)'),
      s('7. Exam traps', 'trap',
        'Razia Sultan was the only woman Sultan of Delhi — a frequently tested standalone fact.',
        'Din-i-Ilahi (Akbar\'s syncretic faith) is not the same as general religious tolerance policy — it was a specific, limited-following faith, not state-imposed.',
        'Sher Shah Suri briefly interrupted Mughal rule between Humayun\'s reigns — he was not a Mughal ruler himself.'),
      s('8. 30-second revision', 'revision',
        'Sultanate: Slave→Khilji→Tughlaq→Sayyid→Lodi (1526). Vijayanagara: Krishnadevaraya, fell at Talikota 1565. Bhakti: Kabir/Nanak/Mira/Tulsidas. Sufi: Chishti. Mughals: Babur-Humayun-Akbar-Jahangir-ShahJahan(TajMahal)-Aurangzeb. Marathas: Shivaji, 1674 coronation.')
    ],
    sourceNote: SRC
  },

  'Modern India': {
    priority: 'MUST KNOW', title: 'Modern India',
    summary: 'European trading companies\' arrival, the East India Company\'s conquest through Plassey (1757) and Buxar (1764), British administrative and economic policy, and the socio-religious reform movements together set the stage that the Freedom Struggle then builds on.',
    sections: [
      p('1. European arrival and East India Company\'s rise', 'must',
        'The Portuguese (Vasco da Gama landed at Calicut in 1498) were the first Europeans to establish a direct sea trade route to India, followed by the Dutch, the English (East India Company, chartered 1600) and the French — of these, the English and French emerged as the two serious rivals for territorial and commercial dominance, contesting each other most directly in the Carnatic Wars in south India. The decisive turning point was the Battle of Plassey (1757), where Robert Clive\'s East India Company forces defeated Siraj-ud-Daulah, the Nawab of Bengal (aided by the betrayal of his commander Mir Jafar), giving the Company effective control of Bengal\'s revenue. The Battle of Buxar (1764), where the Company defeated a combined force of the Nawab of Bengal, the Nawab of Awadh and the Mughal Emperor Shah Alam II, is often considered even more decisive, since it firmly established Company political supremacy in North India and led directly to the Company acquiring Diwani rights (revenue collection authority) over Bengal, Bihar and Odisha in 1765.'),
      p('2. British territorial expansion', 'must',
        'The Company expanded territorial control through a mix of direct conquest and indirect mechanisms: the Subsidiary Alliance system, most aggressively used by Governor-General Wellesley, required allied Indian states to accept a British force (paid for by the state itself) and cede control of foreign policy, effectively reducing them to Company dependents without outright annexation; the Doctrine of Lapse, associated with Governor-General Dalhousie, allowed the Company to annex a princely state if its ruler died without a natural male heir (disallowing adopted heirs for succession purposes) — used to annex states like Satara, Jhansi and Nagpur, and a major grievance feeding into the 1857 revolt.'),
      p('3. The Revolt of 1857', 'must',
        'The Revolt of 1857 (also called the Sepoy Mutiny, or India\'s First War of Independence in nationalist historiography) began with a sepoy mutiny at Meerut, triggered immediately by the greased cartridge controversy (rumoured to be coated with cow and pig fat, offending both Hindu and Muslim soldiers), but rooted in much broader grievances: the Doctrine of Lapse-driven annexations, economic exploitation, and social/religious interference. Bahadur Shah Zafar, the last Mughal emperor, was symbolically declared leader; key regional figures included Rani Lakshmibai of Jhansi, Nana Sahib, and Tantia Tope. The revolt was ultimately suppressed, but its scale prompted a fundamental restructuring: the Government of India Act, 1858 transferred control from the East India Company directly to the British Crown, ending Company rule.'),
      p('4. Socio-religious reform movements', 'understand',
        'Alongside political developments, a wave of socio-religious reform movements challenged social practices and sought religious modernisation: Raja Ram Mohan Roy founded the Brahmo Samaj (1828), campaigning notably against Sati (formally abolished 1829, with Roy\'s advocacy a key factor); Swami Dayananda Saraswati founded the Arya Samaj (1875), advocating a return to Vedic principles and opposing idol worship and caste rigidity; Ramakrishna Paramahansa and his disciple Swami Vivekananda (famous for his 1893 Chicago World Parliament of Religions address) promoted a modernised, universalist interpretation of Vedanta through the Ramakrishna Mission; and Jyotirao Phule campaigned against caste discrimination and for women\'s and lower-caste education in western India — these reform movements are frequently tested as founder-organisation-year associations.'),
      p('5. Economic impact of colonial rule', 'understand',
        'Dadabhai Naoroji\'s "Drain of Wealth" theory, articulated in his book Poverty and Un-British Rule in India, argued that British colonial policy systematically transferred India\'s wealth to Britain through unequal trade, home charges and remittances — a foundational economic critique that shaped early nationalist economic thinking and is frequently cited alongside Naoroji himself as an early Congress moderate leader (also the first Indian elected to the British House of Commons).'),
      s('6. What to memorize', 'must',
        'Plassey (1757, Clive vs Siraj-ud-Daulah, Bengal) → Buxar (1764, Company vs Bengal+Awadh+Mughal emperor) → Diwani rights 1765',
        'Subsidiary Alliance = Wellesley; Doctrine of Lapse = Dalhousie',
        '1857 Revolt: Meerut mutiny trigger, Bahadur Shah Zafar (symbolic leader), Lakshmibai/Nana Sahib/Tantia Tope → GoI Act 1858 (Crown rule begins)',
        'Reform movements: Ram Mohan Roy (Brahmo Samaj, 1828, Sati), Dayananda Saraswati (Arya Samaj, 1875), Vivekananda (Ramakrishna Mission, 1893 Chicago), Phule (caste/women\'s education)',
        'Dadabhai Naoroji = Drain of Wealth theory'),
      s('7. Exam traps', 'trap',
        'Buxar (1764), not Plassey (1757), is generally considered the more politically decisive battle for establishing Company supremacy in North India, though Plassey gave the first major territorial foothold in Bengal.',
        'The Doctrine of Lapse (Dalhousie) and Subsidiary Alliance (Wellesley) are distinct policies by different Governors-General — do not merge them.',
        'The Government of India Act, 1858 ended East India Company rule — it did not grant any self-government to Indians.'),
      s('8. 30-second revision', 'revision',
        'Plassey 1757 (Clive-Siraj) → Buxar 1764 → Diwani 1765. Wellesley=Subsidiary Alliance. Dalhousie=Doctrine of Lapse. 1857: Meerut→Bahadur Shah Zafar→GoI Act 1858. Reforms: Roy(Brahmo,Sati), Dayananda(Arya Samaj), Vivekananda(Ramakrishna Mission). Naoroji=Drain of Wealth.')
    ],
    sourceNote: SRC
  },

  'Freedom Struggle': {
    priority: 'MUST KNOW', title: 'Freedom Struggle',
    summary: 'From the Indian National Congress\'s 1885 founding through the Moderate-Extremist split, Gandhi\'s mass movements, the revolutionary and INA strands, and the final path to 1947, the Freedom Struggle is UKPSC\'s single highest-yield modern-history topic.',
    sections: [
      p('1. Formation of the Indian National Congress and the Moderate phase', 'must',
        'The Indian National Congress was founded in 1885, with A.O. Hume (a retired British civil servant) playing a key organising role and W.C. Bonnerjee as its first president. Its early ("Moderate") phase (roughly 1885-1905), led by figures like Dadabhai Naoroji, Gopal Krishna Gokhale and Pherozeshah Mehta, pursued constitutional methods — petitions, resolutions and dialogue — seeking greater Indian participation in governance rather than full independence, a strategy later Extremists would sharply criticise as insufficiently assertive.'),
      p('2. Partition of Bengal and the rise of the Extremists', 'must',
        'Lord Curzon\'s Partition of Bengal (1905), justified administratively but widely seen as a deliberate attempt to weaken Bengali nationalism by splitting Hindu and Muslim populations, triggered the Swadeshi Movement (boycott of British goods, promotion of indigenous industry) and hardened nationalist sentiment considerably. This fed the rise of the "Extremist" or assertive nationalist wing, led by the trio popularly called "Lal-Bal-Pal" — Lala Lajpat Rai, Bal Gangadhar Tilak (famous for the slogan "Swaraj is my birthright and I shall have it") and Bipin Chandra Pal — who favoured more direct, assertive methods over the Moderates\' petitioning approach; the Congress formally split at the 1907 Surat Session over this strategic divide, reuniting only later (1916, Lucknow Pact). The Muslim League was founded in 1906, partly in response to the same communally charged political environment.'),
      p('3. Gandhi\'s arrival and mass movements', 'must',
        'Mahatma Gandhi returned to India from South Africa in 1915 and first tested his method of Satyagraha (non-violent civil resistance) domestically at Champaran (1917, Bihar, against indigo planters) and Kheda (1918, Gujarat, a peasant tax-relief campaign), before launching it nationally. The Non-Cooperation Movement (1920-22) called for boycotting British institutions, titles and goods, but Gandhi called it off after the Chauri Chaura incident (1922), where a violent mob clash contradicted the movement\'s non-violent principle. The Civil Disobedience Movement (1930-34) began with the Dandi Salt March (Gandhi\'s 240-mile walk to the sea to illegally produce salt, defying the British salt monopoly), spreading into broader law-breaking nationwide. The Quit India Movement (1942), launched with Gandhi\'s call to "Do or Die," demanded immediate British withdrawal and triggered the movement\'s most intense and widespread mass repression, with most Congress leadership imprisoned throughout.'),
      p('4. Revolutionary and armed movements', 'must',
        'Alongside Gandhian non-violence, a parallel revolutionary strand pursued armed resistance: Bhagat Singh, Rajguru and Sukhdev (executed 1931, for the killing of a British police officer in the Lala Lajpat Rai case and the Central Legislative Assembly bombing) are the most iconic figures of the Hindustan Socialist Republican Association (HSRA). Subhas Chandra Bose, after breaking with the mainstream Congress leadership, formed the Indian National Army (INA/Azad Hind Fauj) with Japanese support during WWII, aiming to liberate India through armed struggle from outside British control — his rallying cry "Give me blood, and I shall give you freedom" remains among the most quoted lines of the entire movement.'),
      p('5. The final path to independence', 'must',
        'The Simon Commission (1927), sent to review constitutional reform without any Indian members, was met with the "Simon Go Back" protests and boycotts. The Round Table Conferences (1930-32, London) attempted to negotiate India\'s constitutional future, with Gandhi attending the second (following the Gandhi-Irwin Pact, 1931, which paused Civil Disobedience). The Cripps Mission (1942) offered limited post-war dominion status, rejected by Congress as inadequate — its failure directly preceded the Quit India Movement. After WWII, the Cabinet Mission Plan (1946) attempted a federal solution to avoid partition, but ultimately failed; Lord Mountbatten, the last Viceroy, oversaw the final transfer of power, with the Indian Independence Act, 1947 partitioning British India into India and Pakistan, with independence on 15 August 1947.'),
      s('6. What to memorize', 'must',
        'INC founded 1885 (Hume, Bonnerjee); Partition of Bengal 1905 (Curzon) → Swadeshi; Surat Split 1907 (Moderates vs Extremists/Lal-Bal-Pal); Muslim League 1906',
        'Gandhi: Champaran/Kheda (1917-18) → Non-Cooperation (1920-22, ended after Chauri Chaura) → Civil Disobedience (1930, Dandi March) → Quit India (1942, "Do or Die")',
        'Revolutionaries: Bhagat Singh/Rajguru/Sukhdev (HSRA, executed 1931); Subhas Chandra Bose (INA, "Give me blood...")',
        'Simon Commission (1927, no Indians) → Round Table Conferences (1930-32) → Cripps Mission (1942, rejected) → Cabinet Mission Plan (1946) → Mountbatten Plan → Independence, 15 August 1947'),
      s('7. Exam traps', 'trap',
        'Chauri Chaura (1922) caused Gandhi to withdraw the Non-Cooperation Movement — do not confuse it with Jallianwala Bagh (1919), a separate, earlier massacre that fuelled Non-Cooperation\'s launch in the first place.',
        'The Congress split at Surat was in 1907, over Moderate vs Extremist strategy, reuniting only at Lucknow in 1916.',
        'The Simon Commission had no Indian members at all — a specific, frequently tested detail behind the protests against it.'),
      s('8. 30-second revision', 'revision',
        'INC 1885. Partition of Bengal 1905→Swadeshi. Surat split 1907 (Lal-Bal-Pal). Gandhi: Champaran/Kheda→NonCoop(1920, ends Chauri Chaura 1922)→CivilDisobedience(1930, Dandi)→QuitIndia(1942). Bhagat Singh/HSRA. Bose/INA. Simon(1927)→RTCs(1930-32)→Cripps(1942)→Cabinet Mission(1946)→Independence 15 Aug 1947.')
    ],
    sourceNote: SRC
  },

  'Art & Culture': {
    priority: 'MUST KNOW', title: 'Art & Culture',
    summary: 'Classical dance forms, temple architecture styles (Nagara, Dravida, Vesara), and Hindustani versus Carnatic music are the three pillars of India\'s classical art and culture syllabus, each organised around clear regional and stylistic associations.',
    sections: [
      p('1. Classical dance forms', 'must',
        'India recognises eight classical dance forms, each tied to a specific state/region, worth learning as a fixed list: Bharatanatyam (Tamil Nadu), Kathak (North India, especially Uttar Pradesh, known for intricate footwork and spins), Kathakali (Kerala, elaborate face makeup and costume, dance-drama enacting Hindu epics), Odissi (Odisha), Manipuri (Manipur, associated with Krishna-Radha themes and gentler, flowing movement), Kuchipudi (Andhra Pradesh), Mohiniyattam (Kerala, a solo, graceful "dance of the enchantress"), and Sattriya (Assam, associated with the Vaishnavite monastic institutions, or sattras, founded by Srimanta Sankardev, and given classical status by the Sangeet Natak Akademi in 2000, making it the most recently recognised of the eight). This state-dance pairing is one of the single most reliable, high-frequency GK question formats.'),
      p('2. Temple architecture: Nagara, Dravida and Vesara styles', 'must',
        'Indian temple architecture developed along three broad regional styles: the Nagara style, found across North India, characterised by a curvilinear shikhara (tower) rising directly over the sanctum without a boundary wall (Khajuraho and Odisha\'s Sun Temple at Konark are prime examples); the Dravida style, found in South India, characterised by a stepped, pyramidal vimana (tower) and typically enclosed within elaborate gateway towers called gopurams (the Brihadeeswarar Temple at Thanjavur is a classic example); and the Vesara (or hybrid) style, found particularly in Karnataka (Hoysala temples like Belur and Halebidu), blending elements of both Nagara and Dravida traditions — this three-way classification is a recurring, directly testable framework.'),
      p('3. Indian classical music: Hindustani and Carnatic traditions', 'must',
        'Indian classical music divides into two major traditions: Hindustani classical music, associated with North India and showing greater historical influence from Persian and Central Asian musical traditions (particularly through the Mughal courts), and Carnatic classical music, associated with South India, which retained closer continuity with ancient Sanskrit musical treatises. Both share foundational concepts of raga (melodic framework) and tala (rhythmic cycle) but differ in performance style, instrumentation and repertoire — this Hindustani-versus-Carnatic distinction, along with associating major musicians/instruments to the correct tradition, is a recurring exam theme.'),
      p('4. Other high-yield culture facts', 'understand',
        'Beyond dance, architecture and music, a handful of other culture facts recur: India\'s classical languages (a status conferred by the government, currently including Sanskrit, Tamil, and several others added over time) reflect a language\'s antiquity and independent literary tradition; UNESCO World Heritage Sites in India span cultural and natural categories (the Taj Mahal, Ajanta and Ellora Caves, Khajuraho, and the Western Ghats among them); and the Sangeet Natak Akademi is India\'s national academy for music, dance and drama, the body responsible for conferring official classical-dance status (as it did for Sattriya in 2000).'),
      s('5. What to memorize', 'must',
        'Eight classical dances: Bharatanatyam (TN), Kathak (North India/UP), Kathakali (Kerala), Odissi (Odisha), Manipuri (Manipur), Kuchipudi (AP), Mohiniyattam (Kerala), Sattriya (Assam, added 2000)',
        'Temple styles: Nagara (North, curvilinear shikhara) · Dravida (South, stepped vimana + gopurams) · Vesara (Karnataka, hybrid, Hoysala)',
        'Music: Hindustani (North, Persian-influenced) vs Carnatic (South, closer to ancient Sanskrit tradition)'),
      s('6. Exam traps', 'trap',
        'Kerala has TWO classical dance forms — Kathakali and Mohiniyattam — a frequently tested "more than one dance per state" exception.',
        'Sattriya was added to the classical dance list only in 2000 — the most recent addition, easy to overlook in a "traditional eight" framing.',
        'The Vesara style is regional (Karnataka/Hoysala specifically), not a simple 50-50 blend applied uniformly — do not describe it as generically "found everywhere."'),
      s('7. 30-second revision', 'revision',
        'Dances: Bharatanatyam-TN, Kathak-North, Kathakali+Mohiniyattam-Kerala, Odissi-Odisha, Manipuri-Manipur, Kuchipudi-AP, Sattriya-Assam(2000). Architecture: Nagara-North, Dravida-South, Vesara-Karnataka/Hoysala. Music: Hindustani-North, Carnatic-South.')
    ],
    sourceNote: SRC
  },

  'World History (Basics)': {
    priority: 'IMPORTANT', title: 'World History (Basics)',
    summary: 'A compact survey of the Renaissance, the Industrial and French Revolutions, the two World Wars and the Cold War\'s basic framework — the standard "world history" slice tested alongside India-focused history in most state PSC prelims.',
    sections: [
      p('1. Renaissance and the Industrial Revolution', 'must',
        'The Renaissance ("rebirth"), roughly 14th-17th century Europe, beginning in Italy, marked a revival of classical Greek and Roman learning, humanism and artistic achievement (Leonardo da Vinci, Michelangelo among its most iconic figures), and is conventionally treated as the intellectual bridge between the medieval and modern eras in European history. The Industrial Revolution, beginning in Britain in the mid-18th century, transformed production from artisanal/agrarian methods to mechanised, factory-based manufacturing (the steam engine, associated with James Watt\'s improvements, is its most iconic technology), fundamentally reshaping economies, urbanisation patterns and, significantly for Indian history, the colonial economic relationship discussed under Modern India.'),
      p('2. The American and French Revolutions', 'must',
        'The American Revolution (1775-83) saw Britain\'s thirteen American colonies win independence, formalised through the Declaration of Independence (1776, principally drafted by Thomas Jefferson) and concluded by the Treaty of Paris (1783) — its ideas of natural rights and self-governance influenced later revolutionary movements including, indirectly, French revolutionary thought. The French Revolution (1789-99) overthrew the absolute monarchy (Louis XVI, later executed), driven by Enlightenment ideas, financial crisis and social inequality (the rigid Estates system), and produced the enduring revolutionary slogan "Liberty, Equality, Fraternity" along with the Declaration of the Rights of Man — a foundational moment for modern ideas of citizenship and republicanism that reverberated across 19th-century European and global political thought.'),
      p('3. The Russian Revolution', 'must',
        'The Russian Revolution of 1917 unfolded in two phases: the February Revolution overthrew Tsar Nicholas II\'s monarchy, and the subsequent October Revolution, led by Vladimir Lenin and the Bolshevik Party, established the world\'s first communist state, directly inspiring 20th-century communist and socialist movements globally and setting up the ideological framework (capitalism vs. communism) that would later define the Cold War.'),
      p('4. World War I and World War II', 'must',
        'World War I (1914-18) was triggered by the assassination of Archduke Franz Ferdinand of Austria-Hungary (Sarajevo, 1914), escalating through a web of alliances into a conflict between the Allied Powers and the Central Powers, ending with Germany\'s defeat and the Treaty of Versailles (1919), whose harsh reparations terms are widely cited as a contributing cause of World War II. World War II (1939-45) began with Germany\'s invasion of Poland (1939), pitting the Allied Powers (Britain, later the USSR and USA, among others) against the Axis Powers (Germany, Italy, Japan); its most consequential turning points included the entry of the USA after the Japanese attack on Pearl Harbor (1941), and it ended in 1945 with Germany\'s surrender in Europe and Japan\'s surrender following the atomic bombings of Hiroshima and Nagasaki — the war directly led to the formation of the United Nations (1945) as a successor to the failed League of Nations (formed after WWI).'),
      p('5. The Cold War\'s basic framework', 'understand',
        'The Cold War (roughly 1947-1991) was the prolonged geopolitical and ideological rivalry between the USA-led capitalist bloc (NATO) and the USSR-led communist bloc (Warsaw Pact), characterised by proxy conflicts (Korea, Vietnam), an arms/space race, and the constant background threat of nuclear conflict, rather than direct military confrontation between the two superpowers themselves — it formally ended with the dissolution of the Soviet Union in 1991. India\'s own foreign policy response, the Non-Aligned Movement (co-founded by Jawaharlal Nehru along with leaders like Yugoslavia\'s Tito and Egypt\'s Nasser), positioned newly independent nations as deliberately unaligned with either Cold War bloc — a link worth remembering since it connects this "world history" topic directly back to independent India\'s own foreign policy history.'),
      s('6. What to memorize', 'must',
        'Renaissance (14th-17thC Italy) → Industrial Revolution (mid-18thC Britain, steam engine)',
        'American Revolution 1775-83 (Declaration of Independence 1776); French Revolution 1789-99 (Liberty/Equality/Fraternity)',
        'Russian Revolution 1917: February (Tsar overthrown) → October (Lenin/Bolsheviks, communist state)',
        'WWI 1914-18 (Sarajevo assassination trigger, Treaty of Versailles 1919); WWII 1939-45 (Poland invasion trigger, Pearl Harbor 1941, atomic bombings, UN formed 1945)',
        'Cold War 1947-1991 (USA/NATO vs USSR/Warsaw Pact); Non-Aligned Movement (Nehru, Tito, Nasser)'),
      s('7. Exam traps', 'trap',
        'WWI\'s Treaty of Versailles (1919) is frequently cited as contributing to WWII\'s causes — a cause-effect link worth remembering, not two unrelated events.',
        'The United Nations (1945) replaced the earlier, failed League of Nations (post-WWI) — do not treat them as the same organisation continued.',
        'The Cold War involved no DIRECT military conflict between the USA and USSR — their rivalry played out through proxy wars and an arms race instead.'),
      s('8. 30-second revision', 'revision',
        'Renaissance→Industrial Revolution(Britain, steam engine). American Rev 1776. French Rev 1789 (Liberty-Equality-Fraternity). Russian Rev 1917 (Lenin/Bolsheviks). WWI 1914-18(Versailles 1919)→WWII 1939-45(Pearl Harbor, atomic bombs)→UN 1945. Cold War: USA/NATO vs USSR/Warsaw Pact; NAM=Nehru+Tito+Nasser.')
    ],
    sourceNote: SRC
  }
};
