const p = (heading, type, ...paragraphs) => ({ heading, type, paragraphs });
const s = (heading, type, ...bullets) => ({ heading, type, bullets });

// Progressive rewrite of lib/data.js's indianPolity into explanatory paragraphs.
// Topics not yet listed here fall back to the original bullet version (see the merge
// in app/subjects/polity/[topic]/page.js) — this file only needs the topics done so far.
export const indianPolityExplained = {
  'Constitutional Framework': {
    priority: 'MUST KNOW', title: 'Constitutional Framework of India',
    summary: 'The foundation topic: constitutional evolution under British rule, the Constituent Assembly, the Preamble, and the basic structural organisation of the Constitution. Focus on landmark Acts and what each introduced, not every clause of every pre-independence law.',
    sections: [
      p('1. Constitutional evolution: 1773 to 1919', 'must',
        'Long before 1950, the Constitution\'s institutions were already taking shape under British rule, and understanding that evolution makes later topics like Parliament, federalism and the judiciary far easier. The Regulating Act of 1773 was Parliament\'s first real attempt to control the East India Company, turning the Governor of Bengal into Governor-General (Warren Hastings was the first) with a four-member Executive Council, subordinating Bombay and Madras to Bengal, and setting up a Supreme Court at Calcutta. Pitt\'s India Act of 1784 tightened this further by creating the Board of Control for political oversight alongside the Company\'s own Court of Directors, a "double government" arrangement. The Charter Acts that followed each added something specific: 1813 ended the Company\'s trade monopoly (except tea and China trade) and opened the door to missionaries and education spending; 1833 made the Governor-General of Bengal the Governor-General of India (Lord William Bentinck was first), centralised legislative power and turned the Company into a purely administrative body; and 1853 separated legislative from executive functions in Council and opened the civil services to competitive examination.',
        'The Revolt of 1857 ended Company rule outright: the Government of India Act, 1858 brought India directly under the Crown, created the office of Secretary of State for India, and made the Governor-General also the Viceroy, with Lord Canning first. The Indian Councils Acts of 1861 and 1892 then began, cautiously, associating Indians with legislation, nominating Indians to the councils, restoring some legislative power to Bombay and Madras, and giving members limited budget-discussion and questioning rights.'),
      p('2. Constitutional evolution: 1909 to 1947', 'must',
        'The 20th century brought faster change. The Indian Councils Act of 1909, the Morley-Minto reforms, enlarged the legislative councils and introduced separate electorates for Muslims, with Satyendra Prasad Sinha becoming the first Indian on the Viceroy\'s Executive Council. The Government of India Act of 1919, the Montagu-Chelmsford reforms, introduced dyarchy in the provinces, splitting subjects into Reserved and Transferred categories, and brought bicameralism and direct election at the centre, though the franchise stayed narrow. The Government of India Act of 1935, the most extensive British constitutional law for India, went further still: it abolished provincial dyarchy in favour of full provincial autonomy (while proposing, but never actually implementing, dyarchy and an All-India Federation at the centre), split legislative subjects into Federal, Provincial and Concurrent Lists, and provided for a Federal Court — a structure the later Constitution borrowed heavily from.',
        'Finally, the Indian Independence Act of 1947 created the two independent Dominions of India and Pakistan, ended British paramountcy over the princely states, abolished the Secretary of State for India, and made each Dominion\'s Constituent Assembly a fully sovereign legislature, bringing British rule to a formal end on 15 August 1947.'),
      p('3. The Constituent Assembly', 'must',
        'The Constituent Assembly itself was set up under the Cabinet Mission Plan of 1946, with members chosen indirectly by the Provincial Legislative Assemblies and princely-state representatives nominated rather than elected — it was never chosen by universal adult franchise. It first met on 9 December 1946, with Dr Sachchidananda Sinha as temporary President before Dr Rajendra Prasad took over as permanent President, H.C. Mookherjee as Vice-President and B.N. Rau as Constitutional Adviser (a role distinct from Dr B.R. Ambedkar, who chaired the Drafting Committee appointed on 29 August 1947). Jawaharlal Nehru moved the Objectives Resolution on 13 December 1946, setting out the Constitution\'s philosophical goals; it was adopted on 22 January 1947 and its ideas later shaped the Preamble.',
        'Altogether the Assembly took 2 years, 11 months and 18 days, across 11 sessions and 165 sitting days, to finish its work: the Constitution was adopted on 26 November 1949, though it only came fully into force on 26 January 1950, a date chosen partly to echo the 1930 Purna Swaraj declaration.'),
      p('4. The Preamble', 'must',
        'The Preamble opens with "We, the People of India," making clear the Constitution\'s authority flows from the people, and describes India as a Sovereign, Socialist, Secular, Democratic Republic, securing Justice, Liberty and Equality and promoting Fraternity, the dignity of the individual, and the unity and integrity of the Nation. Only two of those words, Socialist and Secular, were added later, by the 42nd Amendment in 1976, which also changed "unity of the Nation" to "unity and integrity of the Nation" — the Preamble has been amended exactly once. Whether the Preamble even counts as part of the Constitution was itself disputed: the Supreme Court said no in the 1960 Berubari Union opinion, then reversed course in Kesavananda Bharati (1973), holding that it is part of the Constitution and can be amended under Article 368, though not in a way that destroys the Constitution\'s basic structure.'),
      p('5. Salient features, and the parliamentary-federal design', 'understand',
        'India\'s Constitution is written and detailed, drawing on institutions from several countries but adapting them to Indian conditions, and combines a parliamentary system of government with a federal structure carrying a comparatively strong Union, an independent judiciary, Fundamental Rights, Directive Principles, Fundamental Duties, single citizenship, universal adult suffrage, emergency provisions and constitutional local self-government through Panchayats and Municipalities. In the parliamentary system, the President is the constitutional head of the Union executive while real power sits with the Prime Minister and Council of Ministers, who are collectively responsible to the Lok Sabha. And while India divides power between the Union and States through the Union, State and Concurrent Lists, with an independent judiciary to police that division, the Union holds comparatively stronger powers, especially during emergencies, which is why Indian federalism is often described as having both federal and unitary features rather than being a pure federation.'),
      p('6. Article 1, Articles 2-3, and citizenship', 'must',
        'Article 1 declares "India, that is Bharat, shall be a Union of States," deliberately using "Union" rather than "Federation." Article 2 covers admitting or establishing new states, while Article 3 gives Parliament power to form new states or alter the boundaries, area or name of existing ones; a Bill under Article 3 needs the President\'s recommendation, and if it affects a state, that state\'s legislature is asked for its view, but that view is not binding on Parliament — this is exactly how Uttarakhand itself was created. Citizenship at the Constitution\'s commencement is governed by Part II (Articles 5 to 11), with Article 11 letting Parliament legislate further; Parliament used that power to pass the Citizenship Act, 1955, and India follows single citizenship throughout, with no separate state citizenship.'),
      s('7. Parts of the Constitution', 'must',
        'Part I → Union and its Territory', 'Part II → Citizenship', 'Part III → Fundamental Rights', 'Part IV → Directive Principles of State Policy',
        'Part IVA → Fundamental Duties', 'Part V → Union', 'Part VI → States', 'Part IX → Panchayats', 'Part IXA → Municipalities',
        'Part XVIII → Emergency Provisions', 'Part XX → Amendment of the Constitution'),
      s('8. Schedules at a glance', 'must',
        '1st → States and Union Territories', '2nd → emoluments of constitutional authorities', '3rd → forms of oaths and affirmations',
        '4th → allocation of Rajya Sabha seats', '5th → Scheduled Areas and Scheduled Tribes', '6th → tribal areas of Assam, Meghalaya, Tripura, Mizoram',
        '7th → Union, State and Concurrent Lists', '8th → recognised languages', '9th → laws given special constitutional protection',
        '10th → anti-defection', '11th → Panchayats', '12th → Municipalities'),
      s('9. Where the Constitution borrowed from', 'understand',
        'UK → parliamentary government, cabinet system, rule of law, single citizenship', 'US → Fundamental Rights, judicial review, presidential impeachment',
        'Ireland → Directive Principles of State Policy', 'Canada → federation with a strong Centre', 'Australia → Concurrent List',
        'Government of India Act, 1935 → administrative and federal structure'),
      s('10. What to memorize', 'must',
        '9 Dec 1946: first Constituent Assembly meeting; 26 Nov 1949: adopted; 26 Jan 1950: enforced',
        'Ambedkar: Drafting Committee Chairman; B.N. Rau: Constitutional Adviser',
        '1858: Crown replaces Company; 1909: separate electorates; 1919: provincial dyarchy; 1935: provincial autonomy + 3 lists',
        '42nd Amendment: added Socialist, Secular, "integrity of the Nation"'),
      s('11. Exam traps', 'trap',
        'Warren Hastings was the first Governor-General of Bengal, not of India; Bentinck was first GG of India; Canning was first Viceroy.',
        'Dyarchy in the provinces belongs to 1919, not 1935; provincial autonomy is 1935.',
        'Adoption (26 Nov 1949) and commencement (26 Jan 1950) are different dates.',
        'B.N. Rau (Constitutional Adviser) and B.R. Ambedkar (Drafting Committee Chairman) are different roles.',
        'The Constituent Assembly was not elected by universal adult franchise.',
        'Article 1 says "Union of States," not "Federation of States."'),
      s('12. 30-second revision', 'revision',
        '1773 regulation → 1784 Board of Control → 1833 GG of India → 1858 Crown rule → 1909 separate electorate → 1919 provincial dyarchy → 1935 provincial autonomy + 3 lists → 1947 independence. Ambedkar = Drafting Committee; B.N. Rau = Constitutional Adviser. 26 Nov 1949 adopted, 26 Jan 1950 enforced. Preamble = Sovereign Socialist Secular Democratic Republic. Article 1 = Union of States. 42nd Amendment = Socialist + Secular + integrity.')
    ],
    sourceNote: 'UKPSC-focused Constitutional Framework notes based on the Constitution of India and the official UKPSC polity syllabus. Detailed Fundamental Rights, DPSP, Fundamental Duties and Basic Structure doctrine are intentionally reserved for their dedicated Polity topics.'
  }
};
