const SRC = 'Compiled from standard Uttarakhand history references and cross-checked against published sources. Early dynastic dates in Uttarakhand history are debated (family chronicles were compiled centuries later), so where sources differ the notes say so; follow your prescribed book if it differs.';

const s = (heading, type, ...bullets) => ({ heading, type, bullets });

export const uttarakhandHistory = {
  'Ancient Uttarakhand': {
    priority: 'MUST KNOW', title: 'Ancient Uttarakhand',
    summary: 'Ancient Uttarakhand is reconstructed from Puranic and epic references, rock paintings, coins, inscriptions and a few excavated sites. Questions usually test the traditional names of the region, the early tribes, the Kunindas, Ashoka\'s Kalsi edict, the Ashwamedha site at Jagatgram, the Gupta-age Kartripura, the Pauravas and Hiuen Tsang\'s account.',
    sections: [
      s('1. Names of the region and literary sources', 'understand',
        'The Skanda Purana divides the Himalayan region into Kedarkhand (Garhwal) and Manaskhand (Kumaon).',
        'Kumaon is also called Kurmanchal, after the Kurma (tortoise) avatar of Vishnu, traditionally linked with Champawat.',
        'Ancient literature refers to the region as part of the Himalaya or Uttarakuru, and describes peoples such as Kiratas, Khasas, Nagas, Tanganas, Yakshas, Gandharvas and Kinnaras.',
        'The Mahabharata mentions the Kulindas (Kunindas) and their king Subahu among the peoples of the Himalayan region; the Pandavas are traditionally linked with places such as Pandukeshwar and Swargarohini.',
        'Khasas are regarded as one of the most important early communities of the hills; many Katyuri and later society groups trace back to them.'),
      s('2. Prehistoric and protohistoric sites', 'understand',
        'Painted rock shelters: Lakhu Udiyar (Almora, on the Suyal river), Gwarkhya Udiyar (Chamoli) and Kimni (Chamoli).',
        'Copper hoards and ochre-coloured pottery from Bahadrabad (Haridwar) point to Bronze Age contacts with the Gangetic plain.',
        'Purola (Uttarkashi) has yielded evidence of later Harappan/Painted Grey Ware-period settlement.'),
      s('3. Kunindas', 'must',
        'The earliest historically attested ruling power, active during the Sunga and Kushana periods (roughly 2nd century BCE to 3rd century CE).',
        'Known mainly from coins in silver and copper found across Kumaon, Garhwal, and neighbouring Himachal and the Sutlej-Yamuna region.',
        'The best-known king is Amoghabhuti, whose coins carry legends in both Brahmi and Kharoshthi scripts.',
        'Ptolemy places the Kuninda country where the Beas, Sutlej, Yamuna and Ganga rise.'),
      s('4. Mauryan period: Ashoka at Kalsi', 'must',
        'Kalsi (Dehradun district, near the Yamuna-Tons confluence) has a rock inscribed with the complete set of Ashoka\'s 14 Major Rock Edicts, c. 250 BCE.',
        'Language Prakrit, script Brahmi; discovered by John Forbes in 1860.',
        'The rock also carries the figure of an elephant, labelled in Prakrit.',
        'It is a rock edict, not a pillar edict; it shows Mauryan influence reached the Himalayan foothills.'),
      s('5. Post-Mauryan to Gupta period', 'must',
        'Jagatgram (near Vikasnagar, Dehradun) has brick altars of an Ashwamedha yajna; the inscribed bricks name Shilavarman, and the yajna is dated to about the 3rd century CE.',
        'Samudragupta\'s Allahabad (Prayag) Pillar inscription lists Kartripura among the frontier (pratyanta) kingdoms; it is generally identified with the Kumaon-Garhwal-Rohilkhand hills and is sometimes linked with the Kunindas.',
        'The Lakhamandal (Dehradun) inscription of the princess Ishvara records a Yadava line of Sinhapura and a Shiva temple, and is usually placed in the Gupta to Harsha period.'),
      s('6. Harsha, the Pauravas and Hiuen Tsang', 'must',
        'The Chinese traveller Hiuen Tsang (7th century, Harsha\'s time) describes a hill kingdom called Brahmapura; its exact location is debated.',
        'The Paurava (Paurava-Varman) dynasty of Brahmapura is placed between the Harsha period and the Katyuris, with Agnivarman named as founder in Uttarakhand accounts.',
        'After Harsha and the Pauravas, the Katyuris rose as the first dynasty to unite Kumaon and Garhwal.'),
      s('7. Religion and culture', 'understand',
        'Adi Shankaracharya (8th-9th century) established Jyotirmath at Joshimath, one of the four Amnaya maths, and is credited with reviving Badrinath and Kedarnath; tradition says he attained samadhi at Kedarnath.',
        'Buddhism, Shaivism and Vaishnavism co-existed; Kartikeya, Shiva and Vishnu temples spread with the Katyuris.'),
      s('8. Chronology at a glance', 'must',
        'c. 2nd century BCE - 3rd century CE: Kunindas',
        'c. 250 BCE: Ashoka\'s Kalsi edict',
        'c. 3rd century CE: Ashwamedha at Jagatgram (Shilavarman)',
        '4th century CE: Kartripura (Samudragupta\'s inscription)',
        '7th century CE: Hiuen Tsang, Brahmapura, Pauravas',
        '8th-11th century: Katyuris'),
      s('9. Exam traps', 'trap',
        'Kunindas are ancient; Katyuris are early medieval. Do not reverse them.',
        'Kalsi (Ashoka) and Jagatgram (Ashwamedha) are both in Dehradun district but are different sites.',
        'Kedarkhand = Garhwal and Manaskhand = Kumaon are commonly swapped in options.',
        'Kartripura comes from the Allahabad Pillar of Samudragupta, not from a Harsha source.'),
      s('10. 30-second revision', 'revision',
        'Kedarkhand/Manaskhand → rock shelters (Lakhu Udiyar) → Kunindas (Amoghabhuti coins) → Ashoka at Kalsi → Jagatgram Ashwamedha (Shilavarman) → Kartripura (Samudragupta) → Hiuen Tsang/Brahmapura/Pauravas → Shankaracharya (Jyotirmath) → Katyuris.')
    ],
    sourceNote: SRC
  },

  'Katyuri Dynasty': {
    priority: 'MUST KNOW', title: 'Katyuri Dynasty',
    summary: 'The Katyuris are regarded as the first dynasty to rule Kumaon and Garhwal together, with their base in the Katyur (Baijnath) valley. Learn their capitals, inscriptions, rulers named in them, administration, temples and how the kingdom broke up.',
    sections: [
      s('1. Time and origin', 'understand',
        'Traditional accounts give the Katyuri period as roughly the 7th to 11th century CE; some modern scholars place the main Katyuri rulers between about 850 and 1060 CE. Learn "about 8th to 11th century" and note the debate.',
        'Basantan Dev (Vasudev Katyuri) is traditionally treated as the founder.',
        'The name comes from the Katyur (Baijnath) valley in Bageshwar district.'),
      s('2. Capitals', 'must',
        'Kartikeyapura (identified with Joshimath, Chamoli) was the early capital.',
        'The capital later moved to Baijnath in the Katyur valley (Bageshwar).',
        'Dhikuli (near Ramnagar, Nainital) is described as a winter capital.'),
      s('3. Epigraphic sources', 'must',
        'Pandukeshwar copper plates (Chamoli): two plates of Lalitasuradeva, one of Padmatadeva, and one of Subhikshraja (Subhiksharajadeva).',
        'Baleshwar copper plate (Champawat) of Desatadeva.',
        'Stone inscriptions at Bageshwar and Baijnath record the Katyuri royal line.',
        'Copper plates mostly record land grants to Brahmins and temples, which is why they are the main source.'),
      s('4. Rulers named in inscriptions', 'understand',
        'Nimbardeva (Nimbara): said to have started temple building; the tall shikhara/vimana structures at the Jageshwar group of temples are associated with his time.',
        'Ishtaganadeva, Lalitasuradeva and Padmatadeva: rulers linked with the Pandukeshwar copper plates.',
        'Desatadeva and Bhudeva are also named in the inscriptions.',
        'The last generation of rulers ruled a fragmented kingdom.'),
      s('5. Administration', 'understand',
        'The kingdom was divided into mandals (provinces), with village-level self-governing units continuing.',
        'Revenue came from land, forests and trade; land grants (bhumi-dana) to Brahmins and temples raised the standing of the Brahmin class.',
        'Khasa peasants and tribal communities were bound into a common regional culture.'),
      s('6. Temples and architecture', 'must',
        'The Baijnath group of temples (Bageshwar) belongs to the Katyuri period.',
        'Jageshwar (Almora) and Dwarahat (Almora) temple groups are largely attributed to the Katyuri and post-Katyuri periods.',
        'Katyuri temples generally follow the Nagara style in local stone.'),
      s('7. Decline and successors', 'understand',
        'After the 11th century the kingdom broke into smaller principalities in Kumaon, Garhwal and western Nepal (Doti and nearby).',
        'The Chands in Kumaon and the Panwars in Garhwal later became the dominant powers.',
        'The Kumaoni folk ballad Malushahi is set in this period.'),
      s('8. What to memorize', 'must',
        'First dynasty to unify Kumaon and Garhwal: Katyuri',
        'Founder (traditional): Basantan Dev (Vasudev)',
        'Capitals: Kartikeyapura (Joshimath) then Baijnath; winter capital Dhikuli',
        'Copper plates: Pandukeshwar (Lalitasuradeva, Padmatadeva, Subhikshraja); Baleshwar (Desatadeva)',
        'Temples: Baijnath; Jageshwar; Dwarahat'),
      s('9. Exam traps', 'trap',
        'The Katyur valley is in Bageshwar, not Almora; Jageshwar is in Almora, Baijnath in Bageshwar.',
        'Katyuri (Kumaon and Garhwal) is different from Chand (Kumaon only) and Panwar (Garhwal).',
        'Dates for the Katyuri period differ between books; read the wording of the question carefully.'),
      s('10. 30-second revision', 'revision',
        'Katyuri → Basantan Dev → Kartikeyapura (Joshimath) then Baijnath, winter capital Dhikuli → Pandukeshwar and Baleshwar plates → Nimbara and Jageshwar → mandals and land grants → fragmentation → Chands and Panwars.')
    ],
    sourceNote: SRC
  },

  'Chand Dynasty': {
    priority: 'MUST KNOW', title: 'Chand Dynasty of Kumaon',
    summary: 'The Chands were the main power in Kumaon from the medieval period until the Gorkha conquest of 1790. Learn the founder and capitals, the reunification under Ratna Chand, the peak under Rudra Chand and Baz Bahadur Chand, culture and administration, and the decline.',
    sections: [
      s('1. Origin and sources', 'understand',
        'Som (Soma) Chand is traditionally the founder, with the capital at Champawat in Kali Kumaon; family chronicles (vamshavalis) put him around 700 CE, but they were compiled in the 19th century, and some historians place the dynasty\'s rise in the 10th-11th century.',
        'Gyan Chand (14th century) is often treated as the first well-attested ruler of the Champawat line.',
        'The Chands filled the political gap left by the Katyuris and reunited Kumaon in the middle of the 15th century.'),
      s('2. Capitals', 'must',
        'Champawat first, then Almora from 1563 (Kalyan Chand III, also called Balo Kalyan Chand).',
        'Almora remained the capital until the Gorkha conquest of 1790.'),
      s('3. Important rulers', 'must',
        'Ratna Chand (1450-88): reunited Kumaon and is called the first ruler of united Kumaon.',
        'Kalyan Chand III (16th century): made Almora the capital.',
        'Rudra Chand (1565-97): contemporary of Akbar; took Sira in 1581 (defeating Hari Malla); Rudrapur in Udham Singh Nagar is named after him.',
        'Baz Bahadur Chand (1638-78): adopted son of Trimal Chand; expanded the kingdom, and his reign is called the golden age of Kumaon.',
        'Udyot Chand: successor of Baz Bahadur Chand.',
        'Gyan Chand (Guru Gyan Chand) ruled until 1708 and was followed by his son Jagat Chand (1708-20).',
        'Kalyan Chand IV: reign saw the Rohilla raid on Kumaon in the 1740s.',
        'Mahendra Chand (1788-90): last Chand ruler, overthrown by the Gorkhas.'),
      s('4. Administration and society', 'understand',
        'The king ruled with the help of ministers and district-level officials; land grants were issued through copper plates (tamrapatra), an important source of Chand history.',
        'Powerful Joshi ministers (such as Shiv Dev Joshi and Harsh Dev Joshi) controlled court politics in the 18th century.',
        'The Chands cleared and settled the Terai and Bhabar belt, which added revenue; Rudrapur is an example.',
        'Compared with Garhwal, Kumaon had strong Brahmin (Joshi, Pant, Pande and others) and Rajput noble families.'),
      s('5. Religion and culture', 'must',
        'Nanda Devi was the chief deity of the Chand kings; the Nanda Devi temple and fair at Almora belong to this tradition.',
        'Golu Devta, worshipped as the deity of justice, is central to Kumaoni folk religion; the Chitai temple near Almora is the best known.',
        'Temples such as Baleshwar (Champawat) and shrines at Jageshwar received Chand patronage.'),
      s('6. Conflict with Garhwal and decline', 'understand',
        'The Chands and the Panwars of Garhwal fought repeatedly over border areas.',
        'In the 18th century the Rohilla raid, court rivalries and weak kings drained the state.',
        'The Gorkhas took Almora in 1790, ending Chand rule.'),
      s('7. What to memorize', 'must',
        'Founder: Som Chand; first capital Champawat',
        'United Kumaon: Ratna Chand (1450-88)',
        'Capital moved to Almora: 1563, Kalyan Chand III',
        'Rudra Chand: Akbar\'s contemporary, Sira 1581, Rudrapur',
        'Baz Bahadur Chand: 1638-78, golden age',
        'Last ruler: Mahendra Chand; end of rule 1790'),
      s('8. Exam traps', 'trap',
        'Chands ruled Kumaon; Panwars ruled Garhwal.',
        'Do not confuse Rudra Chand (Rudrapur, Akbar) with Baz Bahadur Chand (17th century).',
        'Early Chand dates are uncertain; questions on them usually use the phrase "traditionally".',
        'Chand rule ended in 1790; Gorkha rule ended in 1815.'),
      s('9. 30-second revision', 'revision',
        'Som Chand (Champawat) → Ratna Chand (united Kumaon) → Kalyan Chand III (Almora 1563) → Rudra Chand (Akbar, Rudrapur) → Baz Bahadur Chand (golden age) → Kalyan Chand IV (Rohilla raid) → Mahendra Chand (Gorkhas, 1790).')
    ],
    sourceNote: SRC
  },

  'Panwar / Parmar Dynasty': {
    priority: 'MUST KNOW', title: 'Panwar Dynasty of Garhwal and Tehri State',
    summary: 'The Panwar (Parmar) kings ruled Garhwal from about the 9th century until the Gorkha conquest of 1804, and the Tehri state until 1949. Learn the founders, capital changes, the key rulers of the 17th and 18th centuries, the Gorkha conquest and the Tehri line.',
    sections: [
      s('1. Foundation', 'must',
        'Kanak Pal is the traditional founder, dated 823 CE in some accounts and 888 CE in others; tradition calls him a prince of the Paramara line of Malwa who married into the local ruling house.',
        'The first capital was Chandpurgarhi (Chamoli).',
        'The kingdom was one among 52 small chiefdoms (garhs), and Garhwal ("land of forts") takes its name from them.'),
      s('2. Unification and capital', 'must',
        'Ajay Pal (c. 1493-1519, the 37th ruler) brought the 52 garhs under one rule.',
        'He moved the capital from Chandpurgarhi to Devalgarh and then to Srinagar on the Alaknanda.',
        'Balabhadra Shah (1575-91) was the first Garhwal king to use the title "Shah".'),
      s('3. Mahipati Shah and the generals', 'must',
        'Mahipati Shah (r. 1622-31) asserted independence from the Mughals and expanded towards Tibet.',
        'His main generals were Madho Singh Bhandari, Lodi (Rikhola) and Banwari Das.',
        'Madho Singh Bhandari is remembered as a warrior and administrator; Rikhola Lodi secured borders near Chakrata and Kalsi.'),
      s('4. Rani Karnavati and Prithvipati Shah', 'must',
        'After Mahipati Shah died in 1631, his widow Rani Karnavati ruled as regent for their seven-year-old son Prithvipati Shah.',
        'She is remembered as "Nak Kati Rani" for punishing invading Mughal soldiers.',
        'Prithvipati Shah sheltered the Mughal prince Sulaiman Shikoh, son of Dara Shikoh, in 1658 during the war of succession; Aurangzeb later pressed for his surrender.'),
      s('5. Medini Shah and Fateh Shah', 'understand',
        'Medini Shah succeeded Prithvipati Shah.',
        'Fateh Shah (1684-1716) gave land in the Doon to Guru Ram Rai, whose "Dera" gave Dehradun its name.',
        'Fateh Shah fought Guru Gobind Singh at the Battle of Bhangani (1688) near Paonta Sahib.'),
      s('6. Decline and Gorkha conquest', 'must',
        'Lalit Shah conquered Kumaon around 1779, and his son Pradyumna ruled there as Pradyuman Chand before becoming Garhwal\'s ruler.',
        'Pradyumna Shah (54th ruler, r. 1786-1804) was the last independent king of united Garhwal.',
        'The Gorkhas failed at Langurgarh in 1791 and Garhwal agreed to pay tribute; the 1803 earthquake weakened the kingdom.',
        'In 1804 the Gorkhas defeated and killed Pradyumna Shah at the Battle of Khurbura (Dehradun).'),
      s('7. Tehri Garhwal state', 'must',
        'After the British defeated the Gorkhas, Pradyumna Shah\'s son Sudarshan Shah received the western part of Garhwal in 1815 and made Tehri his capital; the British kept the eastern part (east of the Alaknanda and Mandakini, including Srinagar) as British Garhwal.',
        'Successors: Sudarshan Shah → Bhawani Shah → Pratap Shah (Pratapnagar) → Kirti Shah (Kirtinagar) → Narendra Shah (Narendranagar, 1919) → Manabendra Shah.',
        'The state merged into India on 1 August 1949.'),
      s('8. What to memorize', 'must',
        'Founder: Kanak Pal; first capital: Chandpurgarhi',
        'Unified 52 garhs and moved to Srinagar: Ajay Pal',
        'First to use "Shah": Balabhadra Shah',
        'Mahipati Shah 1622-31; generals Bhandari, Rikhola, Banwari Das',
        'Nak Kati Rani: Karnavati; Sulaiman Shikoh sheltered by Prithvipati Shah (1658)',
        'Guru Ram Rai land grant: Fateh Shah; Bhangani 1688',
        'Langurgarh 1791; Khurbura 1804 (Pradyumna Shah killed)',
        'Tehri: Sudarshan Shah 1815 → Manabendra Shah → merger 1949'),
      s('9. Exam traps', 'trap',
        'Do not confuse Pradyumna Shah (killed 1804) with Sudarshan Shah (Tehri, 1815).',
        'Kanak Pal founded the dynasty; Ajay Pal unified the kingdom.',
        'Kirtinagar, Pratapnagar and Narendranagar are named after three different Tehri kings.',
        'Early dates differ between sources; check the wording ("traditionally") in questions.'),
      s('10. 30-second revision', 'revision',
        'Kanak Pal → Ajay Pal (52 garhs, Srinagar) → Balabhadra Shah (Shah) → Mahipati Shah (Bhandari) → Karnavati → Prithvipati Shah (Sulaiman) → Fateh Shah (Ram Rai) → Pradyumna Shah (Khurbura 1804) → Sudarshan Shah (Tehri 1815) → Narendra Shah → Manabendra Shah (1949).')
    ],
    sourceNote: SRC
  },

  'Gorkha Rule': {
    priority: 'MUST KNOW', title: 'Gorkha Rule in Uttarakhand (1790-1815)',
    summary: 'The Gorkhas of Nepal ruled Kumaon from 1790 and Garhwal from 1804 until the British ended their rule in 1815. Learn the conquest, the commanders, the nature of the rule, the Anglo-Nepal war and the Treaty of Sugauli.',
    sections: [
      s('1. Conquest of Kumaon and Garhwal', 'must',
        'Kumaon: the Gorkhas took Almora in 1790, ending Chand rule under Mahendra Chand; they ruled for about 25 years.',
        'Garhwal: the invasion of 1791 stopped at Langurgarh; Garhwal paid tribute, and in 1803-04 the Gorkhas returned and defeated Pradyumna Shah at Khurbura (January 1804). Garhwal was under them for about 12 years.',
        'Amar Singh Thapa was the overall commander and ruler (Mukhtiyar) of the western provinces; other commanders were Hastidal Chautariya, Bam Shah and Ranjor Thapa.'),
      s('2. Governors', 'understand',
        'Hastidal Chautariya was the first Gorkha governor of Garhwal (1805-08).',
        'Bam Shah was the Gorkha governor of Kumaon and surrendered Almora in 1815.',
        'Amar Singh Thapa was the supreme commander who surrendered at Malaun in 1815.'),
      s('3. Nature of the rule', 'must',
        'The period is remembered as harsh (Gorkhyani), with heavy taxation, forced labour, extortion and slavery; many villages became depopulated.',
        'Kathmandu sometimes issued orders to check abuses by soldiers, but with little effect.',
        'Hastidal made limited efforts to improve agriculture, offering takavi loans to farmers and taxing agriculture at a nominal rate.',
        'The trade in slaves, particularly around the Haridwar fair, became a British grievance.'),
      s('4. Anglo-Nepal War, 1814-16', 'must',
        'Causes: Gorkha expansion, border disputes in the Terai, and British aims of a trade and strategic corridor to the hills.',
        'Battle of Nalapani (Khalanga fort, Dehradun), October-November 1814: British General Gillespie was killed; the Gorkha commander Balbhadra Kunwar (Thapa) held the fort before withdrawing.',
        'Almora fell to British forces on 26-27 April 1815 and Hastidal Chautariya was killed; the British took control of Kumaon on 3 May 1815.',
        'Amar Singh Thapa surrendered at Malaun in May 1815.'),
      s('5. Treaty of Sugauli', 'must',
        'Signed on 2 December 1815 and ratified on 4 March 1816 between the East India Company and Nepal.',
        'Nepal gave up Kumaon, Garhwal, Sikkim and large parts of the Terai; a British Resident was accepted at Kathmandu.',
        'The Kali river became the boundary with Nepal, which is the root of the present Kalapani dispute.',
        'In Garhwal the British kept the eastern part and Dehradun, and gave the western part to Sudarshan Shah (Tehri).'),
      s('6. What to memorize', 'must',
        'Kumaon 1790; Garhwal 1804; end of rule 1815',
        'Langurgarh 1791; Khurbura 1804; Nalapani 1814',
        'Amar Singh Thapa; Hastidal Chautariya (first Garhwal governor 1805-08); Bam Shah',
        'Nalapani: Gillespie killed, Balbhadra Thapa defended',
        'Almora fell April 1815; Sugauli signed 2 Dec 1815, ratified 4 Mar 1816'),
      s('7. Exam traps', 'trap',
        'Khurbura (1804, Garhwal falls) and Nalapani (1814, British war) are different battles, both near Dehradun.',
        'Sugauli is a treaty, not a battle; the dates of signing (Dec 1815) and ratification (Mar 1816) differ.',
        'Gorkha rule lasted about 25 years in Kumaon and about 12 in Garhwal.'),
      s('8. 30-second revision', 'revision',
        '1790 Kumaon → 1791 Langurgarh (Garhwal holds) → 1804 Khurbura (Garhwal falls) → Hastidal governor 1805 → 1814 Nalapani (Gillespie killed) → April 1815 Almora falls → Sugauli (Dec 1815/Mar 1816) → Tehri to Sudarshan Shah.')
    ],
    sourceNote: SRC
  },

  'British Period': {
    priority: 'MUST KNOW', title: 'British Period in Uttarakhand',
    summary: 'British rule began in 1815 and reshaped administration, forests, towns and the army. Learn the non-regulation system, the commissioners, land and forest policy, forced labour, hill stations and institutions, and the military tradition.',
    sections: [
      s('1. Administration', 'must',
        'Edward Gardner was the first Commissioner of Kumaon, appointed on 3 May 1815, with G.W. Traill as assistant; Gardner made the first revenue settlement.',
        'Kumaon and Garhwal were governed as a non-regulation province: the Bengal Regulations did not apply, and one Commissioner held administrative, judicial and revenue powers. This system continued for about seventy years under Traill, Batten and Ramsay.',
        'G.W. Traill (Commissioner to 1835) is remembered for early land settlements and for renaming Halduvani as Haldwani (1834); Traill Pass (Pindari-Milam) is named after him.',
        'In 1839 the region was divided into two districts, Kumaon and Garhwal.',
        'J.H. Batten (1840s to 1856) carried out a major land settlement and promoted tea cultivation.',
        'Henry Ramsay (Commissioner 1856-84) held office so long that he was called the "King of Kumaon"; he was also the first Conservator of Forests in the hills (1858).',
        'A separate Garhwal division was created on 1 December 1968 (after independence).'),
      s('2. Land, forests and forced labour', 'must',
        'Forest reservation began in 1826 with small patches in the lower hills, and widened greatly under Ramsay; this cut off villagers from customary forest use and caused later protests.',
        'Forced labour took three forms: Kuli Utar (carrying baggage of officials), Kuli Begar (unpaid labour) and Kuli Burdayash (free supplies); the practice was given legal sanction in 1913.',
        'Van Panchayats (forest councils) were created in Kumaon in 1931 after long agitation over forest rights.',
        'The Bhotiya traders of the high valleys continued the trade with Tibet through the passes.'),
      s('3. Towns and cantonments', 'must',
        'Mussoorie: 1823, Captain Young; Landour cantonment followed.',
        'Nainital: discovered by P. Barron in 1841 and developed as a hill station.',
        'Chakrata cantonment: 1866; Ranikhet cantonment: 1869; Lansdowne (Garhwal Rifles centre): 1887, named after Viceroy Lansdowne.',
        'Almora, Pauri and Dehradun grew as administrative centres.'),
      s('4. Institutions', 'must',
        'Thomson College of Civil Engineering, Roorkee: 1847, named after James Thomason; it became IIT Roorkee in 2001.',
        'Ganga Canal from Haridwar: begun 1842, opened 1854 under Proby Cautley.',
        'Forest Research Institute, Dehradun: 1906; Indian Military Academy, Dehradun: 1932; Doon School: 1935.'),
      s('5. Army and military tradition', 'must',
        'Garhwal Rifles: raised in 1887 with centre at Lansdowne; it received the "Royal" title in 1921.',
        'Darwan Singh Negi won the Victoria Cross at Festubert (France) in November 1914.',
        'Gabar Singh Negi won the Victoria Cross posthumously at Neuve Chapelle in March 1915.',
        'The Kumaon Regiment has its headquarters at Ranikhet.'),
      s('6. 1857 and after', 'understand',
        'Kalu Singh Mahara of Champawat is remembered as the first freedom fighter of Uttarakhand for his role in the 1857 unrest in Kumaon.',
        'The hills stayed largely under British control in 1857; the Terai and Haldwani area saw more disturbance.'),
      s('7. What to memorize', 'must',
        'First Commissioner: Gardner (3 May 1815); Traill; Batten; Ramsay (1856-84)',
        'Non-regulation province; 1839 two districts',
        'Mussoorie 1823; Nainital 1841; Roorkee college 1847; Ganga Canal 1854',
        'Chakrata 1866; Ranikhet 1869; Lansdowne/Garhwal Rifles 1887',
        'FRI 1906; IMA 1932; Doon School 1935',
        'VCs: Darwan Singh Negi (1914), Gabar Singh Negi (1915)'),
      s('8. Exam traps', 'trap',
        'Gabar Singh Negi (Neuve Chapelle, 1915, posthumous) and Darwan Singh Negi (Festubert, 1914) are often swapped.',
        'Barron discovered Nainital; Young founded Mussoorie.',
        'IIT Roorkee dates to 1847 as a college, not as an IIT.',
        'Coolie Begar was not one practice but three: Utar, Begar and Burdayash.'),
      s('9. 30-second revision', 'revision',
        '1815 Gardner → Traill → Batten → Ramsay; non-regulation province; Mussoorie 1823, Nainital 1841, Roorkee 1847, Ganga Canal 1854; Chakrata 1866, Ranikhet 1869, Garhwal Rifles 1887; FRI 1906, IMA 1932; VCs 1914 and 1915.')
    ],
    sourceNote: SRC
  },

  'Freedom Movement': {
    priority: 'MUST KNOW', title: 'Freedom Movement in Uttarakhand',
    summary: 'The regional freedom movement joined the national struggle with local causes: forced labour, forest rights and autocratic princely rule in Tehri. Learn the organisations, events, dates and leaders in both Kumaon and Garhwal.',
    sections: [
      s('1. Early stirrings', 'understand',
        '1857: Kalu Singh Mahara (Champawat) is regarded as the first freedom fighter of Uttarakhand.',
        'Almora Akhbar (1871), an early newspaper of Kumaon, promoted public opinion.',
        'Kumaon Parishad was formed in 1916 as a social-reform and political body; its leaders included Govind Ballabh Pant, Badri Datt Pandey, Hargovind Pant, Lala Chiranjilal and Victor Mohan Joshi.',
        'Its second session was held at Haldwani in December 1918 under the Garhwali scholar Tara Dutt Gairola, and a resolution moved by Hargovind Pant demanded the end of coolie begar within two years. The Parishad merged with the Congress in 1926.'),
      s('2. Coolie Begar movement, 1921', 'must',
        'Launched on 13-14 January 1921 at the Uttarayani fair of Bageshwar, at the confluence of the Saryu and Gomti.',
        'Led by Badri Datt Pandey, "Kumaon Kesari", with Hargovind Pant, G.B. Pant, Chiranjilal and Victor Mohan Joshi.',
        'Tens of thousands of villagers threw the begar registers into the river and vowed never to do unpaid labour.',
        'Gandhi called it a "bloodless revolution"; the practice ended in the United Provinces in 1921.'),
      s('3. Civil disobedience period, 1929-30', 'must',
        '1929: Gandhi toured Kumaon and wrote Anasakti Yoga at Kausani.',
        '1930: the Salt Satyagraha was followed in the hills; the young Sri Dev Suman was jailed in Agra for taking part.',
        'April 1930, Peshawar Kand: Chandra Singh Garhwali and men of the Garhwal Rifles refused to fire on unarmed protesters.',
        '30 May 1930, Tilari Kand: firing on villagers protesting against the forest policy of the Tehri state in Rawain, often called the "Jallianwala Bagh of Uttarakhand".'),
      s('4. Garhwal politics', 'understand',
        'Barrister Mukundi Lal won the provincial elections of 1923 and 1926 from Garhwal and was a leading Garhwal Congress figure.',
        'Garhwal Congress and Praja Mandals supported the freedom struggle, with Nehru addressing a political conference at Srinagar (Garhwal) in 1938.',
        'In 1942 Quit India protests spread across Kumaon and Garhwal, with arrests in Almora, Nainital and Dehradun.'),
      s('5. Tehri state movement', 'must',
        'Sri Dev Suman (1916-44) founded the Tehri Rajya Praja Mandal in Dehradun in January 1939 and the Himalaya Seva Sangh.',
        'He was arrested on 30 December 1943 and died in Tehri jail on 25 July 1944 after a hunger strike of 84 days.',
        'Kirtinagar movement, January 1948: Nagendra Saklani (Communist Party) and Mola Singh were shot dead on 11 January 1948 while defending the "liberated" Kirtinagar area against the Tehri state forces.',
        'The movement forced the end of monarchy, and Tehri merged with India on 1 August 1949.'),
      s('6. What to memorize', 'must',
        'Kumaon Parishad: 1916; Haldwani session 1918 (Tara Dutt Gairola)',
        'Coolie Begar: Bageshwar, 13-14 Jan 1921, Badri Datt Pandey, Saryu-Gomti',
        'Gandhi at Kausani: 1929 (Anasakti Yoga)',
        'Peshawar Kand April 1930: Chandra Singh Garhwali',
        'Tilari Kand: 30 May 1930, Tehri state',
        'Tehri Praja Mandal: Dev Suman, Jan 1939; died 25 July 1944 after 84 days fast',
        'Kirtinagar: Nagendra Saklani, January 1948; Tehri merger 1 Aug 1949'),
      s('7. Exam traps', 'trap',
        'Tilari Kand occurred in a princely state (Tehri), not in British Kumaon.',
        'Chandra Singh Garhwali (Peshawar) is different from Gabar Singh and Darwan Singh Negi (VC winners).',
        'Badri Datt Pandey led the Coolie Begar in Kumaon; Sri Dev Suman belongs to Tehri.',
        'The Kumaon Parishad was formed in 1916 and merged with the Congress in 1926.'),
      s('8. 30-second revision', 'revision',
        '1857 Kalu Mahara → 1871 Almora Akhbar → 1916 Kumaon Parishad → 1921 Coolie Begar (Bageshwar) → 1929 Gandhi at Kausani → 1930 Peshawar Kand and Tilari Kand → 1939 Tehri Praja Mandal → 1942 Quit India → 1944 Dev Suman dies → 1948 Kirtinagar → 1949 Tehri merges.')
    ],
    sourceNote: SRC
  },

  'Post-Independence Uttarakhand': {
    priority: 'HIGH YIELD', title: 'Post-Independence Uttarakhand (1947-2000)',
    summary: 'Between 1947 and 2000 the region was part of Uttar Pradesh. Learn the merger and renaming, the creation of divisions and districts, key institutions and the military and social developments of the period.',
    sections: [
      s('1. Merger and status', 'must',
        'Kumaon and British Garhwal were already under the United Provinces; Tehri Garhwal merged on 1 August 1949 and became a district of Uttar Pradesh.',
        'The United Provinces were renamed Uttar Pradesh on 24 January 1950.',
        'The hill region remained under the Commissioner of Kumaon until a separate Garhwal division was created on 1 December 1968.'),
      s('2. District creation', 'must',
        '1960: Uttarkashi (24 February 1960, from Tehri), Chamoli (from Garhwal) and Pithoragarh (from Almora) were created.',
        '1995: Udham Singh Nagar (from Nainital).',
        '1997: Rudraprayag, Champawat and Bageshwar.',
        'At formation in 2000 the state had 13 districts: Garhwal division 7 (Dehradun, Haridwar, Pauri, Tehri, Uttarkashi, Chamoli, Rudraprayag) and Kumaon division 6 (Almora, Bageshwar, Champawat, Nainital, Pithoragarh, Udham Singh Nagar).'),
      s('3. Institutions', 'understand',
        'G.B. Pant University of Agriculture and Technology, Pantnagar (1960): India\'s first agricultural university.',
        'Kumaon and Garhwal universities were set up in 1973; Garhwal University was later named after H.N. Bahuguna.',
        'The Oil and Natural Gas Commission and other national institutions are based in Dehradun.'),
      s('4. Military legacy', 'understand',
        'Jaswant Singh Rawat of the Garhwal Rifles (Maha Vir Chakra, posthumous) is remembered for the 1962 Battle of Nuranang.',
        'Major Somnath Sharma of 4 Kumaon received the first Param Vir Chakra (1947).',
        'The Garhwal Rifles and Kumaon Regiment remain central to Uttarakhand\'s identity.'),
      s('5. Social and environmental movements', 'understand',
        'Chipko (1973), Nasha Nahin Rozgar Do (1984) and the anti-Tehri dam agitation grew in this period; they are covered in the Movements section.',
        'Migration from the hills and the sense of neglect in the Lucknow-centred state fed the demand for a separate state.'),
      s('6. What to memorize', 'must',
        'Tehri merger: 1 Aug 1949; UP renamed: 24 Jan 1950; Garhwal division: 1 Dec 1968',
        'Uttarkashi, Chamoli, Pithoragarh: 1960',
        'Udham Singh Nagar: 1995; Rudraprayag, Champawat, Bageshwar: 1997',
        'Pantnagar University 1960; Kumaon and Garhwal universities 1973'),
      s('7. Exam traps', 'trap',
        'Tehri merged in 1949, not 1947 or 1950.',
        'Do not mix the 1960 and 1997 district groups; Udham Singh Nagar is the 1995 district.',
        'Pantnagar is the first agricultural university, not the first university.'),
      s('8. 30-second revision', 'revision',
        '1949 Tehri merges → 1950 UP named → 1960 Uttarkashi, Chamoli, Pithoragarh + Pantnagar → 1968 Garhwal division → 1973 two universities → 1995 US Nagar → 1997 three districts → 2000 state with 13 districts.')
    ],
    sourceNote: SRC
  },

  'Statehood Movement': {
    priority: 'MUST KNOW', title: 'Uttarakhand Statehood Movement',
    summary: 'The demand for a hill state grew over decades and became a mass movement in 1994, leading to statehood on 9 November 2000. Learn the organisations, the 1994 events, the Kaushik Committee and the formation and first office-holders.',
    sections: [
      s('1. Early demands', 'understand',
        'Regional demands for hill-specific governance were raised at Congress and other meetings from the 1930s; in 1938 Nehru addressed a political conference at Srinagar (Garhwal), which is often cited.',
        'The Uttarakhand Kranti Dal (UKD) was founded at Mussoorie on 24 July 1979 with the aim of a separate hill state; D.D. Pant was its first president.',
        'In June 1987 the UKD convention at Karnaprayag pressed the demand, and in November 1987 it passed a resolution for a new state, also asking for Haridwar to be included.',
        'Indramani Badoni, called the "Gandhi of Uttarakhand", was a leading figure of the movement.'),
      s('2. 1994: the mass movement', 'must',
        'The Kaushik Committee, headed by Ramashankar Kaushik (UP Urban Development Minister), submitted its report on 5 May 1994 and recommended a hill state with Gairsain as its capital; the UP government accepted it on 10 August 1994.',
        '1 September 1994: police firing at Khatima (Udham Singh Nagar).',
        '2 September 1994: police firing at Mussoorie.',
        '2 October 1994: police firing at Rampur Tiraha, Muzaffarnagar, on activists travelling to Delhi, with allegations of assault on women activists.'),
      s('3. Formation', 'must',
        'The Uttar Pradesh Reorganisation Bill was passed by Parliament in August 2000 and received the President\'s assent (K.R. Narayanan); the state was created on 9 November 2000 as the 27th state.',
        'It was named Uttaranchal and renamed Uttarakhand on 1 January 2007.',
        'Provisional capital Dehradun; the High Court is at Nainital; Gairsain (Bhararisain) was declared summer capital in 2020.'),
      s('4. First office-holders and chief ministers', 'must',
        'First Governor: Surjit Singh Barnala.',
        'Chief Ministers: Nityanand Swami (9 Nov 2000-29 Oct 2001, first) → Bhagat Singh Koshyari (2001-02) → N.D. Tiwari (2002-07, first elected) → B.C. Khanduri (2007-09) → Ramesh Pokhriyal Nishank (2009-11) → B.C. Khanduri (2011-12) → Vijay Bahuguna (2012-14) → Harish Rawat (2014-17) → Trivendra Singh Rawat (2017-21) → Tirath Singh Rawat (2021) → Pushkar Singh Dhami (2021-).'),
      s('5. What to memorize', 'must',
        'UKD: 24 July 1979, Mussoorie, D.D. Pant',
        'Kaushik Committee: Ramashankar Kaushik, report 5 May 1994; Gairsain capital',
        'Khatima 1 Sept; Mussoorie 2 Sept; Muzaffarnagar (Rampur Tiraha) 2 Oct 1994',
        'State formed 9 Nov 2000 (27th state); renamed 1 Jan 2007',
        'First CM: Nityanand Swami; first elected CM: N.D. Tiwari; first Governor: Surjit Singh Barnala'),
      s('6. Exam traps', 'trap',
        'The formation date (2000) and renaming date (2007) are different.',
        'Nityanand Swami was the first CM; N.D. Tiwari was the first elected CM (after the 2002 elections).',
        'Khatima and Mussoorie (September 1994) are separate from Muzaffarnagar (October 1994).',
        'The Kaushik Committee recommended Gairsain, but the capital stayed provisionally at Dehradun.'),
      s('7. 30-second revision', 'revision',
        'UKD 1979 (Mussoorie) → 1987 Karnaprayag → Kaushik Committee 1994 → Sept-Oct 1994 firings (Khatima, Mussoorie, Muzaffarnagar) → Act 2000 → 9 Nov 2000, 27th state → renamed 2007 → Gairsain summer capital 2020.')
    ],
    sourceNote: SRC
  },

  'Important Historical Personalities': {
    priority: 'HIGH YIELD', title: 'Important Historical Personalities',
    summary: 'A reference list of the people most likely to be asked, grouped by field, with the key fact for each. Match every person with the region, movement and honour.',
    sections: [
      s('1. Freedom fighters and reformers', 'must',
        'Govind Ballabh Pant (1887-1961): born in Almora district; Kumaon Parishad leader, first Premier/Chief Minister of Uttar Pradesh, Union Home Minister; Bharat Ratna 1957.',
        'Badri Datt Pandey (1882-1965): historian and journalist, "Kumaon Kesari", led the Coolie Begar movement; author of History of Kumaon.',
        'Hargovind Pant, Lala Chiranjilal, Victor Mohan Joshi, Tara Dutt Gairola: Kumaon Parishad leaders.',
        'Sri Dev Suman (1916-44): Tehri Praja Mandal; died in Tehri jail after an 84-day fast.',
        'Chandra Singh Garhwali: Peshawar Kand, 1930.',
        'Kalu Singh Mahara: first freedom fighter of Uttarakhand (1857).',
        'Barrister Mukundi Lal: Garhwal leader, won the 1923 and 1926 provincial elections; also known for his work on Garhwal painting.',
        'Jayanand Bharti (1881-1952): led the Dola-Palki movement in Garhwal.',
        'Nagendra Saklani: martyred in the Kirtinagar movement, January 1948.'),
      s('2. Military heroes', 'must',
        'Darwan Singh Negi (1883-1950): Victoria Cross, Festubert, November 1914.',
        'Gabar Singh Negi (1895-1915): Victoria Cross (posthumous), Neuve Chapelle.',
        'Jaswant Singh Rawat (1941-62): Maha Vir Chakra (posthumous), Nuranang, 1962, Garhwal Rifles.'),
      s('3. Environment and social movements', 'must',
        'Gaura Devi: led the women of Reni village in the 1974 Chipko protest.',
        'Chandi Prasad Bhatt: founded the Dasholi Gram Swarajya Sangh at Gopeshwar in 1964, which became the base of the Chipko movement; Ramon Magsaysay Award 1982.',
        'Sundarlal Bahuguna (1927-2021): Chipko leader, later led the anti-Tehri dam movement; Padma Vibhushan 2009.',
        'Sarla Behn (Catherine Mary Heilman, 1901-82): Gandhian who worked in Kumaon, influenced the Chipko leaders.',
        'Kamla Pant: led the Nasha Nahin Rozgar Do movement in Kumaon in 1984.'),
      s('4. Literature, art and exploration', 'understand',
        'Sumitranandan Pant (1900-77): poet born at Kausani; Jnanpith Award 1968 for Chidambara.',
        'Mola Ram (1743-1833): painter and poet of the Garhwal school.',
        'Nain Singh Rawat (born 1830): explorer from Milam (Johar valley) who surveyed Tibet for the British as a "pundit"; Rai Bahadur.',
        'Jim Corbett (1875-1955): hunter-naturalist, author of Man-Eaters of Kumaon; his efforts led to India\'s first national park (1936) in the Nainital region.'),
      s('5. Politics and administration', 'understand',
        'Hemwati Nandan Bahuguna (1919-89): Chief Minister of Uttar Pradesh; Garhwal University is named after him.',
        'Indramani Badoni (1925-99): "Gandhi of Uttarakhand", statehood movement leader.',
        'Nityanand Swami: first Chief Minister of Uttarakhand.'),
      s('6. Rulers to recognise', 'understand',
        'Rani Karnavati: "Nak Kati Rani" of Garhwal.',
        'Pradyumna Shah: killed at Khurbura, 1804.',
        'Kalyan Chand III: moved the Chand capital to Almora; Rudra Chand: Akbar\'s contemporary; Baz Bahadur Chand: golden age of Kumaon.',
        'Amar Singh Thapa and Hastidal Chautariya: Gorkha commanders.'),
      s('7. Exam traps', 'trap',
        'Do not swap Gabar Singh Negi and Darwan Singh Negi.',
        'Chandi Prasad Bhatt (Magsaysay 1982) and Sundarlal Bahuguna (Padma Vibhushan 2009) are both Chipko figures with different honours.',
        'Badri Datt Pandey (Kumaon) and Sri Dev Suman (Tehri) belong to different regions.',
        'Sumitranandan Pant is a poet; Govind Ballabh Pant is the statesman; both are from Almora area.'),
      s('8. 30-second revision', 'revision',
        'G.B. Pant (Bharat Ratna 1957) · Pandey (Kumaon Kesari) · Suman (Tehri, 1944) · Garhwali (Peshawar) · Mahara (1857) · Negis (VCs) · Rawat (Nuranang) · Gaura Devi, Bhatt, Bahuguna (Chipko) · Kamla Pant (1984) · S. Pant (Jnanpith) · Mola Ram (painting) · Nain Singh (Tibet) · Corbett (national park).')
    ],
    sourceNote: SRC
  }
};
