const SRC = 'Compiled from standard Uttarakhand history references and cross-checked against published sources. Early dynastic dates in Uttarakhand history are debated (family chronicles were compiled centuries later), so where sources differ the notes say so; follow your prescribed book if it differs.';

const p = (heading, type, ...paragraphs) => ({ heading, type, paragraphs });
const s = (heading, type, ...bullets) => ({ heading, type, bullets });

export const uttarakhandHistory = {
  'Ancient Uttarakhand': {
    priority: 'MUST KNOW', title: 'Ancient Uttarakhand',
    summary: 'Ancient Uttarakhand is reconstructed from Puranic references, coins, inscriptions and a few excavated sites rather than a continuous political record. The story runs from the Kunindas and Ashoka\'s Kalsi edict, through the Guptas and Kartripura, to Hiuen Tsang\'s Brahmapura and the Pauravas — the dynasty that hands over to the Katyuris.',
    sections: [
      p('1. Names, sources and early peoples', 'understand',
        'Ancient Uttarakhand does not have a single continuous political history the way medieval Kumaon or Garhwal does — most of what we know comes from scattered references in the Puranas and epics, from coins and inscriptions, and from a handful of excavated sites. The Skanda Purana, for instance, splits the region into two halves that still shape how the state is described today: Kedarkhand for Garhwal and Manaskhand for Kumaon. Kumaon carries a second traditional name, Kurmanchal, after the Kurma (tortoise) avatar of Vishnu, usually linked to Champawat.',
        'Early literature places various peoples in this Himalayan belt — Kiratas, Khasas, Nagas, Tanganas, and more mythologically, Yakshas, Gandharvas and Kinnaras. The Mahabharata mentions the Kulindas (an early form of "Kuninda") and a king called Subahu among the Himalayan peoples, and the Pandavas are traditionally connected to sites such as Pandukeshwar and Swargarohini on their final journey. Of the early communities, the Khasas mattered most for what came later: much of the social structure that the Katyuris and later dynasties built on traces back to Khasa society.',
        'Before any of this recorded history, the hills already had human settlement. Rock shelters with painted figures survive at Lakhu Udiyar near Almora, and at Gwarkhya Udiyar and Kimni in Chamoli district. Bronze Age contact with the Gangetic plains shows up in copper hoards and ochre-coloured pottery found at Bahadrabad in Haridwar district, and Purola in Uttarkashi has yielded traces of a later Harappan or Painted Grey Ware-period settlement — signs that the region was never as cut off from the plains as its terrain suggests.'),
      p('2. The Kunindas and Ashoka\'s edict', 'must',
        'The first power in the region we can actually date with confidence is the Kunindas, who ruled roughly from the 2nd century BCE through the Kushana period (up to about the 3rd century CE). We know them almost entirely from their coinage — silver and copper pieces found right across Kumaon, Garhwal, Himachal Pradesh and the upper Sutlej-Yamuna region. Their most recognisable king, Amoghabhuti, issued coins carrying his name in both Brahmi and Kharoshthi script, and the geographer Ptolemy placed the "Kuninda country" exactly where the Beas, Sutlej, Yamuna and Ganga all rise — a fair description of this stretch of the Himalaya.',
        'The clearest physical trace the Mauryas left in the hills is at Kalsi, in Dehradun district near where the Yamuna meets the Tons. A rock there carries the complete set of Ashoka\'s fourteen Major Rock Edicts (a rock edict, not a pillar edict), inscribed in Prakrit using the Brahmi script around 250 BCE, with a carved elephant labelled in the same script. It was rediscovered only in 1860, by John Forbes. Its presence this far into the hills shows Mauryan authority, or at least Mauryan influence, reached well beyond the plains.'),
      p('3. From the Guptas to Harsha', 'must',
        'A few centuries later, at Jagatgram near Vikasnagar in Dehradun district, someone performed an Ashwamedha (horse) sacrifice grand enough to leave behind brick altars — the bricks name a king called Shilavarman, and the site is usually dated to around the 3rd century CE. Around the same broad period, Samudragupta\'s Allahabad Pillar inscription lists a frontier kingdom called Kartripura among the states that paid him tribute; historians generally place Kartripura in the Kumaon-Garhwal-Rohilkhand belt, and some connect it to the declining Kunindas. A separate inscription at Lakhamandal in Dehradun district, commissioned by a princess named Ishvara, records a Yadava dynasty ruling from a place called Sinhapura and the building of a Shiva temple; this too is usually placed somewhere between the Gupta age and Harsha\'s reign.',
        'By the 7th century, when the Chinese pilgrim Hiuen Tsang was travelling through Harsha\'s India, he described a hill kingdom called Brahmapura — though exactly where Brahmapura was is still debated. Uttarakhand\'s own historical tradition places a dynasty called the Pauravas (or Paurava-Varmans), with Agnivarman as founder, ruling from Brahmapura in the gap between Harsha\'s death and the rise of the Katyuris. Whatever the precise political geography, this sets up the story that follows: soon after, the Katyuris would emerge as the first dynasty to bring Kumaon and Garhwal under one rule.'),
      p('4. Religion and culture', 'understand',
        'Religious life in this period cut across sects: Buddhism, Shaivism and Vaishnavism all had a presence, and temples to Kartikeya, Shiva and Vishnu spread as the Katyuri period began. The most consequential religious figure of the era is Adi Shankaracharya, credited with reviving Badrinath and Kedarnath as pilgrimage centres in the 8th or 9th century and with founding Jyotirmath at Joshimath — one of only four Amnaya maths he established across India. Tradition holds that he attained samadhi at Kedarnath itself.'),
      s('5. Chronology at a glance', 'must',
        'c. 2nd century BCE – 3rd century CE: Kunindas',
        'c. 250 BCE: Ashoka\'s Kalsi edict',
        'c. 3rd century CE: Ashwamedha at Jagatgram (Shilavarman)',
        '4th century CE: Kartripura (Samudragupta\'s inscription)',
        '7th century CE: Hiuen Tsang, Brahmapura, Pauravas',
        '8th-11th century: Katyuris'),
      s('6. Exam traps', 'trap',
        'Kunindas are ancient; Katyuris are early medieval. Do not reverse them.',
        'Kalsi (Ashoka) and Jagatgram (Ashwamedha) are both in Dehradun district but are different sites.',
        'Kedarkhand = Garhwal and Manaskhand = Kumaon are commonly swapped in options.',
        'Kartripura comes from the Allahabad Pillar of Samudragupta, not from a Harsha source.'),
      s('7. 30-second revision', 'revision',
        'Kedarkhand/Manaskhand → rock shelters (Lakhu Udiyar) → Kunindas (Amoghabhuti coins) → Ashoka at Kalsi → Jagatgram Ashwamedha (Shilavarman) → Kartripura (Samudragupta) → Hiuen Tsang/Brahmapura/Pauravas → Shankaracharya (Jyotirmath) → Katyuris.')
    ],
    sourceNote: SRC
  },

  'Katyuri Dynasty': {
    priority: 'MUST KNOW', title: 'Katyuri Dynasty',
    summary: 'The Katyuris are regarded as the first dynasty to rule Kumaon and Garhwal together, ruling from the Katyur (Baijnath) valley. Learn where their capitals were, what the copper-plate inscriptions tell us, how the kingdom was run, and how it broke apart into the Chand and Panwar kingdoms.',
    sections: [
      p('1. Origins and capitals', 'understand',
        'Tradition treats Basantan Dev (also called Vasudev Katyuri) as the founder of the Katyuri dynasty, though as with most early Uttarakhand dynasties the dates are debated — older accounts put the Katyuri period as early as the 7th century, while some modern historians confine the main line of rulers to a narrower window, roughly 850 to 1060 CE. What is agreed is that the Katyuris were the first power to rule Kumaon and Garhwal together, and that they took their name from the Katyur valley around Baijnath in present-day Bageshwar district. Their first capital, Kartikeyapura, is generally identified with Joshimath in Chamoli; at some point the capital shifted to Baijnath in the Katyur valley itself, and Dhikuli, near Ramnagar in Nainital district, served as a winter capital lower down in the plains-facing foothills.'),
      p('2. What the inscriptions tell us', 'must',
        'Nearly everything we know about individual Katyuri kings comes from land grants recorded on copper plates and a handful of stone inscriptions — because these grants gave land to Brahmins and temples, they were carefully preserved. The Pandukeshwar copper plates (Chamoli) alone give us Lalitasuradeva (two plates), Padmatadeva and a ruler called Subhikshraja, while a plate found at Baleshwar in Champawat names Desatadeva. Stone inscriptions at Bageshwar and Baijnath add more names to the royal line, including Ishtaganadeva and Bhudeva. One king, Nimbardeva (also written Nimbara), is credited with starting large-scale temple construction — the tall shikhara towers at the Jageshwar temple group in Almora district are usually dated to his reign.'),
      p('3. How the kingdom worked, and how it ended', 'understand',
        'Administratively the Katyuri kingdom was organised into mandals, or provinces, while village-level self-government continued underneath — a pattern common across early medieval Indian states. Revenue came from land, forest produce and trade, and land grants to Brahmins and temples steadily raised the standing of the Brahmin community within Khasa and tribal society, binding different groups into a shared regional culture that outlasted the dynasty itself.',
        'By the 11th century, though, the kingdom had broken apart into a scatter of smaller principalities across Kumaon, Garhwal and parts of western Nepal (the Doti region). Out of that fragmentation the Chands eventually consolidated power in Kumaon and the Panwars in Garhwal — the two dynasties that dominate the rest of medieval Uttarakhand history. The Katyuri period survives today mainly through its temples (the Baijnath group, and much of Jageshwar and Dwarahat) and through folk memory — the popular Kumaoni ballad of Malushahi is set in this era.'),
      s('4. What to memorize', 'must',
        'First dynasty to unify Kumaon and Garhwal: Katyuri',
        'Founder (traditional): Basantan Dev (Vasudev)',
        'Capitals: Kartikeyapura (Joshimath) then Baijnath; winter capital Dhikuli',
        'Copper plates: Pandukeshwar (Lalitasuradeva, Padmatadeva, Subhikshraja); Baleshwar (Desatadeva)',
        'Temples: Baijnath; Jageshwar; Dwarahat'),
      s('5. Exam traps', 'trap',
        'The Katyur valley is in Bageshwar, not Almora; Jageshwar is in Almora, Baijnath in Bageshwar.',
        'Katyuri (Kumaon and Garhwal) is different from Chand (Kumaon only) and Panwar (Garhwal).',
        'Dates for the Katyuri period differ between books; read the wording of the question carefully.'),
      s('6. 30-second revision', 'revision',
        'Katyuri → Basantan Dev → Kartikeyapura (Joshimath) then Baijnath, winter capital Dhikuli → Pandukeshwar and Baleshwar plates → Nimbara and Jageshwar → mandals and land grants → fragmentation → Chands and Panwars.')
    ],
    sourceNote: SRC
  },

  'Chand Dynasty': {
    priority: 'MUST KNOW', title: 'Chand Dynasty of Kumaon',
    summary: 'The Chands were the main power in Kumaon from the medieval period until the Gorkha conquest of 1790. Learn the founder and capitals, the reunification under Ratna Chand, the peak under Rudra Chand and Baz Bahadur Chand, the administration and culture, and the decline.',
    sections: [
      p('1. Origin and rise', 'understand',
        'Family chronicles compiled long after the fact name Som Chand as the founder of the Chand dynasty, ruling from Champawat in the Kali Kumaon area, and place him around 700 CE — but these vamshavalis were written down only in the 19th century, and most historians think the dynasty\'s real rise came later, somewhere in the 10th or 11th century, filling the space left by the collapsing Katyuris. Gyan Chand, in the 14th century, is usually treated as the first Chand ruler for whom we have solid evidence. It took until the mid-15th century for the Chands to reunite Kumaon after generations of fragmentation — a task credited to Ratna Chand (1450-88), sometimes called the first ruler of "united Kumaon."'),
      p('2. Capital and key reigns', 'must',
        'Champawat remained the capital until 1563, when Kalyan Chand III — popularly Balo Kalyan Chand — moved it to Almora, more central to the whole of Kumaon and easier to govern from. Almora stayed the Chand capital for the rest of the dynasty\'s existence. A few reigns stand out along the way. Rudra Chand (1565-97), a contemporary of the Mughal emperor Akbar, pushed Chand authority into the Terai and defeated the Raika ruler Hari Malla to take Sira in 1581; the modern town of Rudrapur, now the headquarters of Udham Singh Nagar district, carries his name.',
        'Baz Bahadur Chand\'s reign (1638-78) is often called the dynasty\'s golden age, marking its greatest territorial reach and its most settled administration. After Baz Bahadur, rulers such as Udyot Chand and the two Gyan-and-Jagat Chand successions kept the kingdom running through the early 18th century, but from Kalyan Chand IV\'s reign onward — which saw a Rohilla raid on Kumaon in the 1740s — court instability set in and never really let up.'),
      p('3. Administration, religion and decline', 'must',
        'Day-to-day government relied on district officials answering to the king, with land grants recorded on copper plates (tamrapatra) that remain a key source for reconstructing Chand history. By the 18th century, however, power had drifted toward powerful minister families rather than the throne itself — the Joshis, most notably Shiv Dev Joshi and later Harsh Dev Joshi, effectively ran the government at times. The Chands were also active builders: Nanda Devi was their chosen deity, and the Nanda Devi temple and fair at Almora carry that patronage forward, while Golu Devta — worshipped across Kumaon as the god of justice, with the Chitai temple near Almora as his best-known shrine — sits at the centre of Kumaoni folk religion more broadly. The Chands also cleared and settled parts of the Terai and Bhabar belt for extra revenue, of which Rudrapur is one result.',
        'None of this saved the dynasty in the end: chronic rivalry with the neighbouring Panwars of Garhwal, weak 18th-century kings, and the Rohilla raid left Kumaon exposed, and in 1790 the invading Gorkhas took Almora, ending Chand rule under its last king, Mahendra Chand.'),
      s('4. What to memorize', 'must',
        'Founder: Som Chand; first capital Champawat',
        'United Kumaon: Ratna Chand (1450-88)',
        'Capital moved to Almora: 1563, Kalyan Chand III',
        'Rudra Chand: Akbar\'s contemporary, Sira 1581, Rudrapur',
        'Baz Bahadur Chand: 1638-78, golden age',
        'Last ruler: Mahendra Chand; end of rule 1790'),
      s('5. Exam traps', 'trap',
        'Chands ruled Kumaon; Panwars ruled Garhwal.',
        'Do not confuse Rudra Chand (Rudrapur, Akbar) with Baz Bahadur Chand (17th century).',
        'Early Chand dates are uncertain; questions on them usually use the phrase "traditionally".',
        'Chand rule ended in 1790; Gorkha rule ended in 1815.'),
      s('6. 30-second revision', 'revision',
        'Som Chand (Champawat) → Ratna Chand (united Kumaon) → Kalyan Chand III (Almora 1563) → Rudra Chand (Akbar, Rudrapur) → Baz Bahadur Chand (golden age) → Kalyan Chand IV (Rohilla raid) → Mahendra Chand (Gorkhas, 1790).')
    ],
    sourceNote: SRC
  },

  'Panwar / Parmar Dynasty': {
    priority: 'MUST KNOW', title: 'Panwar Dynasty of Garhwal and Tehri State',
    summary: 'The Panwar (Parmar) kings ruled Garhwal from about the 9th century until the Gorkha conquest of 1804, and the Tehri state until 1949. Learn the founder and the unification of the 52 garhs, the key 17th-century rulers, the Gorkha conquest, and the Tehri line that followed.',
    sections: [
      p('1. Founding and unification', 'must',
        'The Panwar (or Parmar) line of Garhwal traces itself to Kanak Pal, traditionally dated to 823 CE in some accounts and 888 CE in others, and said to be a prince of the Paramara house of Malwa who married into the local ruling family and took the throne. His capital was Chandpurgarhi in present-day Chamoli district. At the time Garhwal was really a patchwork of 52 small forts, or garhs, each under its own local chief — Garhwal\'s very name, "land of forts," comes from this.',
        'It took until the reign of Ajay Pal, the dynasty\'s 37th ruler (roughly 1493-1519), for all 52 garhs to be brought under one crown. Ajay Pal moved the capital twice more, first to Devalgarh and then to Srinagar on the Alaknanda, where it stayed for the rest of the kingdom\'s independent existence. A little later, Balabhadra Shah (1575-91) became the first Garhwal king to adopt the title "Shah," which his successors kept.'),
      p('2. The 17th-century kings', 'must',
        'Mahipati Shah, who ruled from 1622 to 1631, is remembered for standing up to Mughal pressure and pushing Garhwal\'s influence toward Tibet, with the help of three able generals — Madho Singh Bhandari, Lodi (also called Rikhola), and Banwari Das. Bhandari in particular is remembered as both a soldier and an administrator, while Rikhola Lodi is credited with securing the borders near Chakrata and Kalsi. When Mahipati Shah died young in 1631, his widow, Rani Karnavati, ruled as regent for their seven-year-old son Prithvipati Shah — and earned the nickname "Nak Kati Rani" ("nose-cutting queen") for her harsh treatment of invading Mughal soldiers.',
        'Once he came of age, Prithvipati Shah made his own mark in Mughal politics: in 1658, during the war of succession that followed Shah Jahan\'s illness, he gave shelter to the fugitive prince Sulaiman Shikoh (son of Dara Shikoh), which later brought pressure from Aurangzeb demanding the prince\'s surrender. A couple of generations on, Fateh Shah (1684-1716) granted land in the Doon valley to the Sikh spiritual leader Guru Ram Rai — whose settlement, or "Dera," is why the town is called Dehradun — and also fought, and lost to, Guru Gobind Singh at the Battle of Bhangani in 1688, near Paonta Sahib.'),
      p('3. Decline, the Gorkha conquest, and the Tehri line', 'must',
        'Garhwal\'s independence unravelled in the late 18th century. Around 1779 the Garhwal king Lalit Shah conquered Kumaon, installing his son Pradyuman there as a Chand-style ruler before that son, Pradyumna Shah, took the Garhwal throne himself and became its 54th and last independent king. The Gorkhas invaded from the east in 1791 but were stopped at Langurgarh, after which Garhwal agreed to pay tribute; a devastating earthquake in 1803 weakened the kingdom further, and in January 1804 the Gorkhas returned, defeated Garhwal\'s forces at the Battle of Khurbura near Dehradun, and killed Pradyumna Shah. Garhwal\'s independent history ends there.',
        'Once the British later defeated the Gorkhas in 1815, Pradyumna Shah\'s son Sudarshan Shah was given back the western half of the old kingdom and made Tehri his new capital, while the British kept the eastern half, including the old capital Srinagar, as "British Garhwal." The Tehri line continued through Sudarshan Shah\'s successors — Bhawani Shah, Pratap Shah (who founded Pratapnagar), Kirti Shah (Kirtinagar), Narendra Shah (who founded Narendranagar in 1919) and finally Manabendra Shah — until the princely state merged into independent India on 1 August 1949.'),
      s('4. What to memorize', 'must',
        'Founder: Kanak Pal; first capital: Chandpurgarhi',
        'Unified 52 garhs and moved to Srinagar: Ajay Pal',
        'First to use "Shah": Balabhadra Shah',
        'Mahipati Shah 1622-31; generals Bhandari, Rikhola, Banwari Das',
        'Nak Kati Rani: Karnavati; Sulaiman Shikoh sheltered by Prithvipati Shah (1658)',
        'Guru Ram Rai land grant: Fateh Shah; Bhangani 1688',
        'Langurgarh 1791; Khurbura 1804 (Pradyumna Shah killed)',
        'Tehri: Sudarshan Shah 1815 → Manabendra Shah → merger 1949'),
      s('5. Exam traps', 'trap',
        'Do not confuse Pradyumna Shah (killed 1804) with Sudarshan Shah (Tehri, 1815).',
        'Kanak Pal founded the dynasty; Ajay Pal unified the kingdom.',
        'Kirtinagar, Pratapnagar and Narendranagar are named after three different Tehri kings.',
        'Early dates differ between sources; check the wording ("traditionally") in questions.'),
      s('6. 30-second revision', 'revision',
        'Kanak Pal → Ajay Pal (52 garhs, Srinagar) → Balabhadra Shah (Shah) → Mahipati Shah (Bhandari) → Karnavati → Prithvipati Shah (Sulaiman) → Fateh Shah (Ram Rai) → Pradyumna Shah (Khurbura 1804) → Sudarshan Shah (Tehri 1815) → Narendra Shah → Manabendra Shah (1949).')
    ],
    sourceNote: SRC
  },

  'Gorkha Rule': {
    priority: 'MUST KNOW', title: 'Gorkha Rule in Uttarakhand (1790-1815)',
    summary: 'The Gorkhas of Nepal ruled Kumaon from 1790 and Garhwal from 1804 until the British ended their rule in 1815. Learn the conquest, what "Gorkhyani" meant for ordinary people, the Anglo-Nepal War, and the Treaty of Sugauli that redrew the region\'s borders.',
    sections: [
      p('1. Conquest and administration', 'must',
        'The Gorkha kingdom of Nepal expanded westward into Kumaon in 1790, defeating the last Chand ruler Mahendra Chand and taking Almora; Kumaon then stayed under Gorkha rule for about 25 years. Garhwal held out longer: a first Gorkha push in 1791 was stopped at Langurgarh and Garhwal paid tribute instead of being annexed outright, but the Gorkhas returned in force in 1803-04 and, helped by a kingdom already weakened by an earthquake, defeated and killed Pradyumna Shah at the Battle of Khurbura in January 1804, bringing Garhwal under Gorkha rule for roughly the next 12 years. Overall command of the newly won western provinces lay with Amar Singh Thapa, who governed as Mukhtiyar (something like a viceroy); under him, officers such as Hastidal Chautariya (Garhwal\'s first Gorkha governor, 1805-08), Bam Shah and Ranjor Thapa administered the conquered territories.',
        'The period the hills still remember as "Gorkhyani" was harsh: heavy taxation, forced labour, extortion, and a slave trade, particularly around the Haridwar fair, that later gave the British a moral pretext for war. Kathmandu occasionally issued orders against the worst abuses by its own soldiers, with limited effect, and villages emptied out under the pressure. Hastidal did make some effort to improve agriculture, offering takavi (agricultural) loans and keeping the land-tax rate nominal, but this did little to soften the period\'s reputation.'),
      p('2. The Anglo-Nepal War and the end of Gorkha rule', 'must',
        'Border disputes in the Terai, continued Gorkha expansion, and British ambitions for a trade route into the hills brought the two sides to war in 1814. The best-remembered engagement in Uttarakhand is the siege of Nalapani (Khalanga fort, near Dehradun) in October-November 1814, where the Gorkha commander Balbhadra Kunwar held out long enough to kill the British General Rollo Gillespie before eventually withdrawing. The war turned decisively in the British favour through early 1815: Almora fell on 26-27 April, Hastidal Chautariya was killed in the fighting, and Kumaon passed formally to British control on 3 May 1815; Amar Singh Thapa surrendered at Malaun that same month.',
        'The Treaty of Sugauli, signed on 2 December 1815 and ratified on 4 March 1816, ended the war: Nepal gave up Kumaon, Garhwal, Sikkim and large stretches of the Terai, and accepted a British Resident at Kathmandu. The Kali river became the new boundary with Nepal, a line still disputed today around Kalapani. In Garhwal, the British kept the eastern part (with Dehradun) directly and handed the western part back to Sudarshan Shah, creating the separate princely state of Tehri Garhwal.'),
      s('3. What to memorize', 'must',
        'Kumaon 1790; Garhwal 1804; end of rule 1815',
        'Langurgarh 1791; Khurbura 1804; Nalapani 1814',
        'Amar Singh Thapa; Hastidal Chautariya (first Garhwal governor 1805-08); Bam Shah',
        'Nalapani: Gillespie killed, Balbhadra Thapa defended',
        'Almora fell April 1815; Sugauli signed 2 Dec 1815, ratified 4 Mar 1816'),
      s('4. Exam traps', 'trap',
        'Khurbura (1804, Garhwal falls) and Nalapani (1814, British war) are different battles, both near Dehradun.',
        'Sugauli is a treaty, not a battle; the dates of signing (Dec 1815) and ratification (Mar 1816) differ.',
        'Gorkha rule lasted about 25 years in Kumaon and about 12 in Garhwal.'),
      s('5. 30-second revision', 'revision',
        '1790 Kumaon → 1791 Langurgarh (Garhwal holds) → 1804 Khurbura (Garhwal falls) → Hastidal governor 1805 → 1814 Nalapani (Gillespie killed) → April 1815 Almora falls → Sugauli (Dec 1815/Mar 1816) → Tehri to Sudarshan Shah.')
    ],
    sourceNote: SRC
  },

  'British Period': {
    priority: 'MUST KNOW', title: 'British Period in Uttarakhand',
    summary: 'British rule began in 1815 and reshaped administration, forests, towns and the army. Learn the non-regulation system and its three long-serving Commissioners, how forests and forced labour were controlled, the hill stations and institutions that date from this period, and the region\'s military tradition.',
    sections: [
      p('1. A non-regulation province', 'must',
        'Once the war ended, Kumaon (and later Garhwal) was placed under a single Commissioner rather than the ordinary Bengal Regulations — a deliberately looser system known as "non-regulation," in which one officer combined administrative, judicial and revenue powers. Edward Gardner, appointed on 3 May 1815 with G.W. Traill as his assistant, was the first Commissioner and carried out the earliest revenue settlement. Traill then held the post himself until 1835, renaming the town of Halduvani to Haldwani in 1834 and leaving his name on the Traill Pass between the Pindari and Milam valleys; the region was split into the separate districts of Kumaon and Garhwal in 1839.',
        'J.H. Batten (through the 1840s to 1856) carried out a major land settlement and pushed tea cultivation in the hills, and Henry Ramsay\'s long tenure as Commissioner (1856-84) — he also served as the hills\' first Conservator of Forests from 1858 — earned him the nickname "King of Kumaon." This non-regulation arrangement, run in succession by Traill, Batten and Ramsay, lasted roughly seventy years; a separate Garhwal division was only created much later, on 1 December 1968, well after independence.'),
      p('2. Land, forests and forced labour', 'must',
        'British rule steadily tightened control over the hills\' forests, starting with small reserved patches in 1826 and expanding sharply under Ramsay, cutting villagers off from grazing and fuelwood rights they had always taken for granted and storing up resentment that would surface repeatedly in the 20th century. Alongside this, the colonial government relied on unpaid local labour in three distinct forms — Kuli Utar (carrying officials\' baggage), Kuli Begar (general unpaid work) and Kuli Burdayash (compulsory free supplies) — a system given formal legal backing in 1913. It took sustained agitation before the government created Van Panchayats (village forest councils) in 1931, giving communities some formal say over local forest management. Through all of this, Bhotiya traders in the high valleys kept up their traditional trade with Tibet across the Himalayan passes.'),
      p('3. Hill stations, institutions and the army', 'must',
        'The British era gave Uttarakhand many of its best-known towns. Captain Young founded Mussoorie in 1823 (with the Landour cantonment following soon after), and P. Barron is credited with discovering Nainital in 1841, which grew into the principal summer retreat of the United Provinces government. Cantonments followed at Chakrata (1866) and Ranikhet (1869), and Lansdowne was established in 1887 as the depot of the newly raised Garhwal Rifles, named for the then Viceroy. The period also left lasting institutions: Thomson College of Civil Engineering at Roorkee (1847, later IIT Roorkee from 2001), the Ganga Canal from Haridwar (begun 1842, opened 1854 under engineer Proby Cautley), the Forest Research Institute at Dehradun (1906), the Indian Military Academy at Dehradun (1932) and the Doon School (1935).',
        'Military service became, and remains, central to the region\'s identity: the Garhwal Rifles, raised in 1887, produced two of the era\'s most celebrated soldiers — Darwan Singh Negi, who won the Victoria Cross at Festubert in November 1914, and Gabar Singh Negi, awarded the Victoria Cross posthumously at Neuve Chapelle in March 1915. The 1857 uprising touched the hills only lightly — Kalu Singh Mahara of Champawat, remembered as the region\'s first freedom fighter, is linked to unrest that year, but the real disturbance was concentrated further south around the Terai and Haldwani.'),
      s('4. What to memorize', 'must',
        'First Commissioner: Gardner (3 May 1815); Traill; Batten; Ramsay (1856-84)',
        'Non-regulation province; 1839 two districts',
        'Mussoorie 1823; Nainital 1841; Roorkee college 1847; Ganga Canal 1854',
        'Chakrata 1866; Ranikhet 1869; Lansdowne/Garhwal Rifles 1887',
        'FRI 1906; IMA 1932; Doon School 1935',
        'VCs: Darwan Singh Negi (1914), Gabar Singh Negi (1915)'),
      s('5. Exam traps', 'trap',
        'Gabar Singh Negi (Neuve Chapelle, 1915, posthumous) and Darwan Singh Negi (Festubert, 1914) are often swapped.',
        'Barron discovered Nainital; Young founded Mussoorie.',
        'IIT Roorkee dates to 1847 as a college, not as an IIT.',
        'Coolie Begar was not one practice but three: Utar, Begar and Burdayash.'),
      s('6. 30-second revision', 'revision',
        '1815 Gardner → Traill → Batten → Ramsay; non-regulation province; Mussoorie 1823, Nainital 1841, Roorkee 1847, Ganga Canal 1854; Chakrata 1866, Ranikhet 1869, Garhwal Rifles 1887; FRI 1906, IMA 1932; VCs 1914 and 1915.')
    ],
    sourceNote: SRC
  },

  'Freedom Movement': {
    priority: 'MUST KNOW', title: 'Freedom Movement in Uttarakhand',
    summary: 'The regional freedom movement joined the national struggle with local causes: forced labour, forest rights and autocratic princely rule in Tehri. Learn the Kumaon Parishad and Coolie Begar movement, the 1930 protests at Peshawar and Tilari, and the separate struggle inside the Tehri princely state.',
    sections: [
      p('1. From early organisation to the Kumaon Parishad', 'understand',
        'Organised political activity in the hills grew slowly through the late 19th century — the Almora Akhbar newspaper, founded in 1871, was an early platform for local opinion — before consolidating in 1916 with the formation of the Kumaon Parishad, part social-reform body and part political forum, led by figures including Govind Ballabh Pant, Badri Datt Pandey, Hargovind Pant, Lala Chiranjilal and Victor Mohan Joshi. Its second session, held at Haldwani in December 1918 under the Garhwali scholar Tara Dutt Gairola, passed a resolution moved by Hargovind Pant demanding an end to coolie begar (forced labour) within two years, a demand the Parishad would eventually see through. The Parishad itself merged into the Indian National Congress in 1926.'),
      p('2. The Coolie Begar movement and Gandhi\'s visit', 'must',
        'The campaign against forced labour reached its climax at the Uttarayani fair in Bageshwar on 13-14 January 1921, where Badri Datt Pandey — soon to be honoured with the title "Kumaon Kesari" — led tens of thousands of villagers, alongside Hargovind Pant, G.B. Pant, Chiranjilal and Victor Mohan Joshi, in throwing the official begar registers into the confluence of the Saryu and Gomti rivers and swearing never to perform unpaid labour again. Gandhi later called it a "bloodless revolution," and the practice did in fact collapse across the United Provinces that same year. Gandhi visited Kumaon himself in 1929, writing his commentary Anasakti Yoga while staying at Kausani, a stay the town still commemorates.'),
      p('3. 1930 and after: Peshawar, Tilari and Quit India', 'must',
        'The civil disobedience movement of 1930 touched Uttarakhand in two very different ways. In April that year, soldiers of the Garhwal Rifles posted to Peshawar, led by Chandra Singh Garhwali, refused an order to fire on unarmed protesters, an act of defiance remembered as the Peshawar Kand. A month later, on 30 May 1930, the princely state of Tehri responded to protests against its forest policy in the Rawain area with a firing that killed several farmers at Tilari, an episode still called the "Jallianwala Bagh of Uttarakhand."',
        'Barrister Mukundi Lal, who won successive provincial elections from Garhwal in 1923 and 1926, kept up political pressure through the Garhwal Congress in the years that followed, and in 1938 Nehru addressed a political conference at Srinagar (Garhwal). When the Quit India movement arrived in 1942, it produced arrests and protests across both Kumaon and Garhwal, including at Almora, Nainital and Dehradun.'),
      p('4. The struggle inside Tehri state', 'must',
        'Because Tehri remained a princely state under its own Maharaja rather than direct British rule, its freedom movement was really a struggle against monarchy itself. Sri Dev Suman founded the Tehri Rajya Praja Mandal at Dehradun in January 1939, along with the Himalaya Seva Sangh, to campaign for civil rights and against autocratic rule; declared a rebel and arrested on 30 December 1943, he died in Tehri jail on 25 July 1944 after an 84-day hunger strike, becoming the movement\'s best-known martyr. The struggle culminated after independence, when the Kirtinagar movement of January 1948, during which Communist Party activist Nagendra Saklani and Mola Singh were shot dead defending the area from the state\'s forces, helped force the issue, and Tehri finally merged into the Indian Union on 1 August 1949.'),
      s('5. What to memorize', 'must',
        'Kumaon Parishad: 1916; Haldwani session 1918 (Tara Dutt Gairola)',
        'Coolie Begar: Bageshwar, 13-14 Jan 1921, Badri Datt Pandey, Saryu-Gomti',
        'Gandhi at Kausani: 1929 (Anasakti Yoga)',
        'Peshawar Kand April 1930: Chandra Singh Garhwali',
        'Tilari Kand: 30 May 1930, Tehri state',
        'Tehri Praja Mandal: Dev Suman, Jan 1939; died 25 July 1944 after 84 days fast',
        'Kirtinagar: Nagendra Saklani, January 1948; Tehri merger 1 Aug 1949'),
      s('6. Exam traps', 'trap',
        'Tilari Kand occurred in a princely state (Tehri), not in British Kumaon.',
        'Chandra Singh Garhwali (Peshawar) is different from Gabar Singh and Darwan Singh Negi (VC winners).',
        'Badri Datt Pandey led the Coolie Begar in Kumaon; Sri Dev Suman belongs to Tehri.',
        'The Kumaon Parishad was formed in 1916 and merged with the Congress in 1926.'),
      s('7. 30-second revision', 'revision',
        '1857 Kalu Mahara → 1871 Almora Akhbar → 1916 Kumaon Parishad → 1921 Coolie Begar (Bageshwar) → 1929 Gandhi at Kausani → 1930 Peshawar Kand and Tilari Kand → 1939 Tehri Praja Mandal → 1942 Quit India → 1944 Dev Suman dies → 1948 Kirtinagar → 1949 Tehri merges.')
    ],
    sourceNote: SRC
  },

  'Post-Independence Uttarakhand': {
    priority: 'HIGH YIELD', title: 'Post-Independence Uttarakhand (1947-2000)',
    summary: 'Between 1947 and 2000 the region was part of Uttar Pradesh. Learn how Tehri merged and the province was renamed, how new districts were carved out over five decades, the institutions built during this period, and how out-migration and neglect fed the demand for a separate state.',
    sections: [
      p('1. Merger, renaming and administrative growth', 'must',
        'Kumaon and the eastern (British) part of Garhwal were already administered as part of the United Provinces, and Tehri Garhwal joined them as a district on 1 August 1949, once the princely state agreed to merge. The United Provinces itself was renamed Uttar Pradesh a few months later, on 24 January 1950. For nearly two more decades the whole hill region stayed under a single Kumaon Commissioner, until a separate Garhwal division was finally carved out on 1 December 1968, recognition, in administrative terms, that the two halves of the future state needed to be governed somewhat separately.'),
      p('2. New districts and institutions', 'must',
        'District boundaries kept shifting through this period as the hills\' population grew. Uttarkashi was created out of Tehri on 24 February 1960, alongside Chamoli (from Garhwal) and Pithoragarh (from Almora) the same year. Udham Singh Nagar followed in 1995, carved from Nainital, and Rudraprayag, Champawat and Bageshwar were all created in 1997. By the time Uttarakhand became a separate state in 2000, this process had left it with 13 districts — seven in Garhwal division (Dehradun, Haridwar, Pauri, Tehri, Uttarkashi, Chamoli, Rudraprayag) and six in Kumaon division (Almora, Bageshwar, Champawat, Nainital, Pithoragarh, Udham Singh Nagar).',
        'The same decades built up the institutions the state would inherit: G.B. Pant University of Agriculture and Technology at Pantnagar, India\'s first agricultural university, opened in 1960, and separate Kumaon and Garhwal universities followed in 1973 (Garhwal University later took the name of H.N. Bahuguna). National bodies such as the Oil and Natural Gas Commission also set up major operations in Dehradun during this period.'),
      p('3. Military honours and the roots of the statehood demand', 'understand',
        'The region\'s military tradition continued to produce recognised heroes — Major Somnath Sharma of 4 Kumaon received India\'s first Param Vir Chakra in 1947, and Rifleman Jaswant Singh Rawat of the Garhwal Rifles was posthumously awarded the Maha Vir Chakra for the 1962 Battle of Nuranang. But beneath these achievements, a quieter problem was building: continued out-migration from the hills, and a growing sense that a state government based in distant Lucknow paid little attention to the hill districts\' needs. That frustration, together with the environmental and social movements of the 1970s and 1980s — Chipko, and later the anti-liquor and anti-Tehri-dam campaigns, covered separately under Movements — fed directly into the demand for a separate hill state that would dominate Uttarakhand politics from the late 1970s onward.'),
      s('4. What to memorize', 'must',
        'Tehri merger: 1 Aug 1949; UP renamed: 24 Jan 1950; Garhwal division: 1 Dec 1968',
        'Uttarkashi, Chamoli, Pithoragarh: 1960',
        'Udham Singh Nagar: 1995; Rudraprayag, Champawat, Bageshwar: 1997',
        'Pantnagar University 1960; Kumaon and Garhwal universities 1973'),
      s('5. Exam traps', 'trap',
        'Tehri merged in 1949, not 1947 or 1950.',
        'Do not mix the 1960 and 1997 district groups; Udham Singh Nagar is the 1995 district.',
        'Pantnagar is the first agricultural university, not the first university.'),
      s('6. 30-second revision', 'revision',
        '1949 Tehri merges → 1950 UP named → 1960 Uttarkashi, Chamoli, Pithoragarh + Pantnagar → 1968 Garhwal division → 1973 two universities → 1995 US Nagar → 1997 three districts → 2000 state with 13 districts.')
    ],
    sourceNote: SRC
  },

  'Statehood Movement': {
    priority: 'MUST KNOW', title: 'Uttarakhand Statehood Movement',
    summary: 'The demand for a hill state grew over decades and became a mass movement in 1994, leading to statehood on 9 November 2000. Learn how the Uttarakhand Kranti Dal organised the demand, what happened at Khatima, Mussoorie and Muzaffarnagar in 1994, and how the new state and its first leaders took shape.',
    sections: [
      p('1. From scattered demands to an organised party', 'understand',
        'Calls for separate governance of the hill districts go back to the colonial period and resurfaced at various Congress gatherings in the 1930s and 1940s — Nehru\'s 1938 visit to a political conference at Srinagar (Garhwal) is often cited from this period. The demand only became an organised political movement with the founding of the Uttarakhand Kranti Dal (UKD) at Mussoorie on 24 July 1979, with D.D. Pant as its first president; the party made a separate hill state its central goal. Momentum built through the 1980s: a UKD convention at Karnaprayag in June 1987 pressed the case again, and a resolution that November went further still, demanding the inclusion of Haridwar in the proposed state. Indramani Badoni, remembered as the "Gandhi of Uttarakhand," emerged as one of the movement\'s most respected leaders during this period.'),
      p('2. 1994: from committee report to mass agitation', 'must',
        'The turning point came in 1994. A committee headed by Ramashankar Kaushik, then UP\'s Urban Development Minister, submitted its report on 5 May 1994 recommending a separate hill state with its capital at Gairsain, and the state government formally accepted the recommendation on 10 August. Rather than settling the matter, this triggered a wave of protest, and a correspondingly harsh response. Police opened fire on demonstrators at Khatima, in present-day Udham Singh Nagar, on 1 September 1994, and again the very next day at Mussoorie. The worst incident came a month later: on the night of 2 October 1994, police fired on statehood activists travelling toward Delhi at Rampur Tiraha near Muzaffarnagar, in an episode that also involved serious allegations of assault on women protesters. These killings hardened public opinion and made statehood, rather than any lesser administrative reform, the only acceptable outcome.'),
      p('3. Formation and the first years of the new state', 'must',
        'Parliament passed the Uttar Pradesh Reorganisation Bill in August 2000, and with President K.R. Narayanan\'s assent the new state came into being on 9 November 2000, India\'s 27th state, initially named Uttaranchal, with its capital provisionally at Dehradun and its High Court at Nainital. It would be renamed Uttarakhand only later, on 1 January 2007, and Gairsain (Bhararisain), the capital the Kaushik Committee had originally recommended back in 1994, was finally declared the state\'s summer capital in 2020, though Dehradun remains the seat of government for most of the year. Surjit Singh Barnala became the state\'s first Governor, and Nityanand Swami its first Chief Minister; it took until the 2002 elections, and the appointment of N.D. Tiwari, for Uttarakhand to have its first elected Chief Minister.'),
      s('4. What to memorize', 'must',
        'UKD: 24 July 1979, Mussoorie, D.D. Pant',
        'Kaushik Committee: Ramashankar Kaushik, report 5 May 1994; Gairsain capital',
        'Khatima 1 Sept; Mussoorie 2 Sept; Muzaffarnagar (Rampur Tiraha) 2 Oct 1994',
        'State formed 9 Nov 2000 (27th state); renamed 1 Jan 2007',
        'First CM: Nityanand Swami; first elected CM: N.D. Tiwari; first Governor: Surjit Singh Barnala'),
      s('5. Exam traps', 'trap',
        'The formation date (2000) and renaming date (2007) are different.',
        'Nityanand Swami was the first CM; N.D. Tiwari was the first elected CM (after the 2002 elections).',
        'Khatima and Mussoorie (September 1994) are separate from Muzaffarnagar (October 1994).',
        'The Kaushik Committee recommended Gairsain, but the capital stayed provisionally at Dehradun.'),
      s('6. 30-second revision', 'revision',
        'UKD 1979 (Mussoorie) → 1987 Karnaprayag → Kaushik Committee 1994 → Sept-Oct 1994 firings (Khatima, Mussoorie, Muzaffarnagar) → Act 2000 → 9 Nov 2000, 27th state → renamed 2007 → Gairsain summer capital 2020.')
    ],
    sourceNote: SRC
  },

  'Important Historical Personalities': {
    priority: 'HIGH YIELD', title: 'Important Historical Personalities',
    summary: 'A reference list of the people most likely to be asked, grouped by field, with the key fact for each. Read it after the topics above — most of these names have already appeared with their full context there; this page is for cross-checking and quick recall.',
    sections: [
      p('1. Freedom fighters and reformers', 'must',
        'Govind Ballabh Pant, born in Almora district (1887-1961), is by far the most nationally prominent figure from the hills: a Kumaon Parishad leader who went on to become the first Chief Minister of Uttar Pradesh and later Union Home Minister, earning the Bharat Ratna in 1957. Badri Datt Pandey (1882-1965), the "Kumaon Kesari" who led the Coolie Begar movement and wrote History of Kumaon, worked alongside fellow Parishad leaders Hargovind Pant, Lala Chiranjilal, Victor Mohan Joshi and Tara Dutt Gairola.',
        'In Tehri state, Sri Dev Suman (1916-44) led the fight against princely autocracy and died after an 84-day fast, while Nagendra Saklani gave his life in the same cause at Kirtinagar in 1948. Chandra Singh Garhwali is remembered for the Peshawar Kand of 1930, Kalu Singh Mahara of Champawat as the region\'s earliest (1857) freedom fighter, and Barrister Mukundi Lal as Garhwal\'s leading Congress politician of the 1920s, later also known for his writing on Garhwal painting. Jayanand Bharti led the separate Dola-Palki movement for social equality in Garhwal.'),
      p('2. Military heroes', 'must',
        'Three names from the hills\' military tradition come up repeatedly. Darwan Singh Negi (1883-1950) won the Victoria Cross at Festubert in November 1914; Gabar Singh Negi (1895-1915) won his posthumously at Neuve Chapelle a few months later, in March 1915, the two are easy to mix up, but the battle and the "posthumous" detail tell them apart. Jaswant Singh Rawat (1941-62) of the Garhwal Rifles received the Maha Vir Chakra, also posthumously, for his stand at the 1962 Battle of Nuranang.'),
      p('3. Environmental and social reformers', 'must',
        'Gaura Devi led the women of Reni village in the defining Chipko protest of 1974; Chandi Prasad Bhatt, who founded the Dasholi Gram Swarajya Sangh at Gopeshwar in 1964, is regarded as the movement\'s organisational founder and won the Ramon Magsaysay Award in 1982, while Sundarlal Bahuguna (1927-2021) carried Chipko\'s message nationally before leading the long campaign against the Tehri Dam, and received the Padma Vibhushan in 2009. Sarla Behn, born Catherine Mary Heilman, was the Gandhian whose work in Kumaon shaped this generation of environmentalists. Kamla Pant led the Nasha Nahin Rozgar Do (anti-liquor, pro-employment) movement in Kumaon in 1984.'),
      p('4. Literature, art, exploration and politics', 'understand',
        'Sumitranandan Pant (1900-77), born at Kausani, won the Jnanpith Award in 1968 for his poetry collection Chidambara; Mola Ram (1743-1833) is remembered as the leading painter and poet of the Garhwal school; and Nain Singh Rawat, born in 1830 in the Bhotiya village of Milam, became one of the great 19th-century explorers, secretly surveying Tibet for the British as a "pundit" and earning the title Rai Bahadur. Jim Corbett (1875-1955), the hunter-turned-conservationist whose books include Man-Eaters of Kumaon, made his home at Kaladhungi and was instrumental in the creation of India\'s first national park in the Nainital area in 1936.',
        'In politics, Hemwati Nandan Bahuguna (1919-89) rose to become Chief Minister of Uttar Pradesh and is honoured today in the name of Garhwal University, while Indramani Badoni and Nityanand Swami, the "Gandhi of Uttarakhand" and the new state\'s first Chief Minister respectively, both belong to the statehood-movement generation covered in more detail in that topic.'),
      s('5. Exam traps', 'trap',
        'Do not swap Gabar Singh Negi and Darwan Singh Negi.',
        'Chandi Prasad Bhatt (Magsaysay 1982) and Sundarlal Bahuguna (Padma Vibhushan 2009) are both Chipko figures with different honours.',
        'Badri Datt Pandey (Kumaon) and Sri Dev Suman (Tehri) belong to different regions.',
        'Sumitranandan Pant is a poet; Govind Ballabh Pant is the statesman; both are from the Almora area.'),
      s('6. 30-second revision', 'revision',
        'G.B. Pant (Bharat Ratna 1957) · Pandey (Kumaon Kesari) · Suman (Tehri, 1944) · Garhwali (Peshawar) · Mahara (1857) · Negis (VCs) · Rawat (Nuranang) · Gaura Devi, Bhatt, Bahuguna (Chipko) · Kamla Pant (1984) · S. Pant (Jnanpith) · Mola Ram (painting) · Nain Singh (Tibet) · Corbett (national park).')
    ],
    sourceNote: SRC
  }
};
